"""Pure text builders for every generated workspace artifact.

Standard-library only, no I/O: each function returns the exact file *content* as a
string, so tests can assert on the rendered text and planners can wrap it in a
``write_text_file_command``. All generated artifacts are **English** (they are
technical and portable); the app's own UI is what gets translated, not these.

Odoo config keys, ``addons_path`` composition, and the source-install flow are
anchored to the official Odoo "Source install" and CLI / ``odoo.conf`` reference
pages (see docs/).
"""

from __future__ import annotations

import json
import shlex
from xml.sax.saxutils import escape

from . import egress, tester
from .models import (
    LEGACY_LAYOUT_MAX_MAJOR,
    UV_PYTHON,
    InstanceConfig,
    InterpreterChoice,
    MigrationEnv,
    WorkspaceConfig,
    migration_interpreter,
    odoo_major,
    python_tuple,
    requirement_substitute,
    setuptools_requirement,
    version_support,
)


def _gevent_port_key(version: str) -> str:
    """Live-chat/bus port key: ``gevent_port`` on Odoo ≥ 16, else ``longpolling_port``."""
    return "gevent_port" if odoo_major(version) >= 16 else "longpolling_port"


def _smtp_to_capture() -> list[str]:
    """Outgoing mail goes to the local capture (Mailpit): shown there when it runs,
    refused when it does not — never delivered. A mail server stored in the
    database takes precedence over these keys; see the mail redirect action."""
    return [
        "; Mail goes to the local capture (Mailpit); never delivered. docs/egress-control.md",
        f"smtp_server = {egress.MAILPIT_SMTP_HOST}",
        f"smtp_port = {egress.MAILPIT_SMTP_PORT}",
    ]


def render_odoo_conf(cfg: WorkspaceConfig, version: str) -> str:
    """Render a development ``odoo.conf`` for one instance of the workspace.

    Development posture: ``workers = 0`` (threaded, debugger-friendly), the
    composed ``addons_path``, the derived per-version HTTP port, and a separate
    bus port. Keys are the official ``odoo.conf`` options.
    """
    http_port = cfg.http_port_for(version)
    bus_port = http_port + 1000
    lines = [
        "[options]",
        "; Generated by odoo_dwg — development configuration.",
        f"addons_path = {cfg.addons_path(version)}",
        "",
        "http_interface = 127.0.0.1",
        f"http_port = {http_port}",
        f"{_gevent_port_key(version)} = {bus_port}",
        "",
        "; Development posture: threaded mode so the debugger can attach.",
        "workers = 0",
        "max_cron_threads = 1",
        # No `reload`: it re-executes the process as soon as watchdog is
        # installed, which detaches the debugger every launch config attaches.
        "dev_mode = qweb,xml",
        "",
        f"db_host = {cfg.db_host}",
        f"db_port = {cfg.db_port}",
        f"db_user = {cfg.db_user}",
        "admin_passwd = admin",
        "",
        *_smtp_to_capture(),
    ]
    return "\n".join(lines) + "\n"


def requirements_install_command(pip: str, requirements: str, version: str) -> str:
    """``pip install -r`` of a branch's requirements, with any substitute applied:
    the dropped project's line is filtered out and its replacement installed in
    the same resolution (see ``models.REQUIREMENT_SUBSTITUTES``)."""
    substitute = requirement_substitute(version)
    if substitute is None:
        return f"{shlex.quote(pip)} install -r {shlex.quote(requirements)}"
    dropped, replacement = substitute
    pattern = shlex.quote(f"^{dropped}([=<>!~; ]|$)")
    return (
        # pipefail: without it only pip's status is seen, so an unreadable
        # requirements file would install the substitute alone and report [OK].
        f"set -o pipefail && grep -v -i -E {pattern} {shlex.quote(requirements)} | "
        f"{shlex.quote(pip)} install -r /dev/stdin {shlex.quote(replacement)}"
    )


def render_setup_venv_sh(
    cfg: WorkspaceConfig,
    interpreters: dict[str, InterpreterChoice] | None = None,
) -> str:
    """A reproducible bash script that (re)builds every instance venv and installs
    its version-matched requirements from the shared repo cache.

    ``interpreters`` must be the same resolved choices the generation plan used:
    a version whose venv the plan builds with a ``uv``-provided interpreter has to
    be rebuilt the same way here, or re-running this script would quietly replace
    it with the host ``python3`` — the exact breakage the support matrix exists to
    prevent."""
    header = [
        "#!/usr/bin/env bash",
        "# Generated by odoo_dwg — create/refresh the per-version virtualenvs.",
        "set -euo pipefail",
        "",
    ]
    blocks: list[str] = []
    for inst in cfg.instances():
        venv = cfg.venv_dir(inst.version)
        odoo = cfg.odoo_clone_dir(inst.version)
        choice = (interpreters or {}).get(inst.version)
        if choice and choice.source == UV_PYTHON and choice.python:
            create = [
                f'# Odoo {inst.version} supports Python {version_support(inst.version).python_range_text()}',
                f"uv venv --seed --no-project --python {shlex.quote(choice.python)} "
                f"{shlex.quote(str(venv))}",
            ]
        else:
            create = [f"python3 -m venv {shlex.quote(str(venv))}"]
        marker = cfg.venv_ready_marker(inst.version)
        blocks.append(
            "\n".join(
                [
                    f"echo {shlex.quote(f'[odoo{inst.major}] creating venv {venv}')}",
                    # Clear the ready marker first and write it last: neither
                    # `uv venv --seed` nor `python3 -m venv` removes it, so a run
                    # that dies between them would leave a half-built venv wearing
                    # the marker that tells every later flow to skip it.
                    f"rm -f {shlex.quote(str(marker))}",
                    *create,
                    f"{shlex.quote(f'{venv}/bin/pip')} install --upgrade pip wheel "
                    f"{shlex.quote(setuptools_requirement(inst.version))}",
                    requirements_install_command(
                        f"{venv}/bin/pip", f"{odoo}/requirements.txt", inst.version
                    ),
                    f"touch {shlex.quote(str(marker))}",
                    "",
                ]
            )
        )
    return "\n".join(header + blocks)


def render_run_sh(cfg: WorkspaceConfig, version: str) -> str:
    """A bash launcher for one instance (venv python + odoo-bin + its conf)."""
    inst = InstanceConfig(cfg.name, version)
    venv = cfg.venv_dir(version)
    odoo = cfg.odoo_clone_dir(version)
    conf = cfg.config_file(version)
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# Generated by odoo_dwg — run the {inst.name} instance.",
            "set -euo pipefail",
            f"exec {shlex.quote(f'{venv}/bin/python')} {shlex.quote(f'{odoo}/odoo-bin')} "
            f'-c {shlex.quote(str(conf))} "$@"',
            "",
        ]
    )


def render_vscode_settings(cfg: WorkspaceConfig) -> str:
    default = cfg.versions[0]
    settings = {
        "python.defaultInterpreterPath": str(cfg.venv_dir(default) / "bin" / "python"),
        "python.terminal.activateEnvironment": True,
        # The official Odoo language server analyses Python; Pylance doing the
        # same would duplicate (and contradict) its diagnostics. The Python
        # extension stays for debugging and interpreter selection.
        "python.languageServer": "None",
        "files.exclude": {"**/__pycache__": True, "**/*.pyc": True},
        "search.exclude": {"**/.venv": True, "**/.repos": True},
    }
    return json.dumps(settings, indent=2) + "\n"


# The official Odoo extension and the language server it runs (odoo/odoo-vscode,
# odoo/odoo-ls). See docs/editor-integration.md for the update procedure.
ODOO_EXTENSION_ID = "Odoo.odoo"

# The OdooLS release this configuration was last reviewed against. Bump it in
# the change that adopts what a review of newer releases found, never alone:
# tools/verify_odools_config.py reports the release notes since this version.
ODOOLS_REVIEWED_VERSION = "1.4.0"

# The only keys emitted per profile: the "minimal config file" of the OdooLS
# documentation. The schema is strict (additionalProperties: false), so an
# unknown key breaks the whole file; these four are in every stable schema on
# record. Keys documented as applying from a given release (the 1.5 JavaScript
# options, semantic-token switches) and template variables are deliberately
# never emitted — they are exactly what changes between releases.
ODOOLS_KEYS: tuple[str, ...] = ("name", "odoo_path", "addons_paths", "python_path")

# OdooLS refuses Odoo below this major ("only supports version 14 and above").
ODOOLS_MIN_ODOO_MAJOR = 14


def odools_versions(cfg: WorkspaceConfig) -> list[str]:
    """The workspace versions the official language server can open."""
    return [v for v in cfg.versions if odoo_major(v) >= ODOOLS_MIN_ODOO_MAJOR]


def _toml_string(value: str) -> str:
    """A TOML basic string. JSON's string escaping is a valid subset of TOML's
    (backslash, quote, control characters, \\uXXXX), so it quotes paths safely."""
    return json.dumps(value, ensure_ascii=False)


def render_odools_toml(cfg: WorkspaceConfig) -> str:
    """The official Odoo language server's configuration: one profile per version.

    The workspace opens only its own root while Odoo lives in the shared cache
    outside it — often in several versions — so OdooLS's zero-config detection
    cannot find it. Each profile states the four facts the generator already
    knows, as absolute paths. Core add-ons are loaded by OdooLS from
    ``odoo_path``, so ``addons_paths`` lists the workspace's own directories only."""
    lines = [
        "# Generated by odoo_dwg — profiles for the official Odoo language server",
        f"# (OdooLS, reviewed against {ODOOLS_REVIEWED_VERSION}). Pick one from the status bar.",
        "# Only the documented minimal keys are set; add your own below if you need more.",
    ]
    skipped = [v for v in cfg.versions if v not in odools_versions(cfg)]
    if skipped:
        lines.append(
            f"# No profile for {', '.join(skipped)}: OdooLS supports Odoo "
            f"{ODOOLS_MIN_ODOO_MAJOR} and above only."
        )
    for inst in cfg.instances():
        if inst.version not in odools_versions(cfg):
            continue
        addons = ", ".join(
            _toml_string(str(path)) for path in cfg.addons_dirs(inst.version, include_core=False)
        )
        values = {
            "name": _toml_string(f"{cfg.name} {inst.version}"),
            "odoo_path": _toml_string(str(cfg.odoo_clone_dir(inst.version))),
            "addons_paths": f"[{addons}]",
            "python_path": _toml_string(str(cfg.venv_dir(inst.version) / "bin" / "python")),
        }
        lines += ["", "[[config]]"] + [f"{key} = {values[key]}" for key in ODOOLS_KEYS]
    return "\n".join(lines) + "\n"


def render_vscode_extensions() -> str:
    recommendations = {
        "recommendations": [
            "ms-python.python",
            "ms-python.debugpy",
            ODOO_EXTENSION_ID,
        ]
    }
    return json.dumps(recommendations, indent=2) + "\n"


def render_vscode_tasks(cfg: WorkspaceConfig) -> str:
    tasks = {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Setup venvs",
                "type": "shell",
                "command": "bash scripts/setup_venv.sh",
                "problemMatcher": [],
            }
        ]
        + [
            {
                "label": f"Run odoo{odoo_major(v)}",
                "type": "shell",
                "command": f"bash scripts/run-odoo{odoo_major(v)}.sh",
                "problemMatcher": [],
            }
            for v in cfg.versions
        ],
    }
    return json.dumps(tasks, indent=2) + "\n"


# Debug entry points per version, beyond serving: Odoo's interactive shell, a
# server that upgrades modules on start, and one module's tests. Each asks what
# it needs at launch through the ``inputs`` below (``${input:<id>}``).
LAUNCH_INPUT_DATABASE = "odooDatabase"
LAUNCH_INPUT_MODULES = "odooModules"
LAUNCH_INPUT_TEST_MODULE = "odooTestModule"


def _launch_inputs(cfg: WorkspaceConfig) -> list[dict]:
    return [
        {
            "id": LAUNCH_INPUT_DATABASE,
            "type": "promptString",
            "description": "Odoo database",
            "default": cfg.name,
        },
        {
            "id": LAUNCH_INPUT_MODULES,
            "type": "promptString",
            "description": "Modules to upgrade (comma-separated)",
        },
        {
            "id": LAUNCH_INPUT_TEST_MODULE,
            "type": "promptString",
            "description": "Module whose tests to run",
        },
    ]


def _launch_configuration(cfg: WorkspaceConfig, version: str, name: str, args: list[str]) -> dict:
    return {
        "name": name,
        "type": "debugpy",
        "request": "launch",
        "python": str(cfg.venv_dir(version) / "bin" / "python"),
        "program": str(cfg.odoo_clone_dir(version) / "odoo-bin"),
        "args": args,
        "console": "integratedTerminal",
        "justMyCode": False,
    }


def render_vscode_launch(cfg: WorkspaceConfig) -> str:
    """Four debug configurations per version: serve, shell, upgrade modules and
    test one module. All run ``odoo-bin`` from the version's venv under debugpy."""
    database = f"${{input:{LAUNCH_INPUT_DATABASE}}}"
    modules = f"${{input:{LAUNCH_INPUT_MODULES}}}"
    test_module = f"${{input:{LAUNCH_INPUT_TEST_MODULE}}}"
    configurations = []
    for inst in cfg.instances():
        conf = str(cfg.config_file(inst.version))
        label = f"Odoo {inst.version}"
        suffix = f"({inst.name})"
        configurations += [
            _launch_configuration(cfg, inst.version, f"{label} {suffix}", ["-c", conf]),
            _launch_configuration(
                cfg, inst.version, f"{label} shell {suffix}",
                ["shell", "-c", conf, "-d", database],
            ),
            _launch_configuration(
                cfg, inst.version, f"{label} upgrade modules {suffix}",
                ["-c", conf, "-d", database, "-u", modules],
            ),
            _launch_configuration(
                cfg, inst.version, f"{label} test module {suffix}",
                ["-c", conf, "-d", database, "-u", test_module, "--test-enable",
                 "--test-tags", f"/{test_module}", "--stop-after-init"],
            ),
        ]
    launch = {"version": "0.2.0", "configurations": configurations, "inputs": _launch_inputs(cfg)}
    return json.dumps(launch, indent=2) + "\n"


def render_code_workspace(cfg: WorkspaceConfig) -> str:
    workspace = {
        "folders": [{"path": "."}],
        "settings": {"python.terminal.activateEnvironment": True},
    }
    return json.dumps(workspace, indent=2) + "\n"


def _readme_python(choice: InterpreterChoice | None) -> str:
    if choice is None or not choice.python:
        return "host `python3`"
    label = f"{choice.python} (`uv`)" if choice.source == UV_PYTHON else f"{choice.python} (host)"
    # Said in English, like the rest of this file: `InterpreterChoice.describe`
    # is for the UI and is translated, and a generated artifact never is.
    return f"{label} — **outside the supported range**" if choice.out_of_range else label


def _readme_requirement_changes(version: str) -> str:
    substitute = requirement_substitute(version)
    if substitute is None:
        return "—"
    dropped, replacement = substitute
    return f"`{replacement}` instead of `{dropped}`"


def render_workspace_readme(
    cfg: WorkspaceConfig,
    interpreters: dict[str, InterpreterChoice] | None = None,
) -> str:
    """A robust per-workspace README giving any human or AI full context —
    versions, layout, per-version ports/configs, what each venv installs, and
    setup/run commands. ``interpreters`` are the choices the plan built with."""
    version_rows = "\n".join(
        f"| {inst.version} | `{inst.name}` | {cfg.http_port_for(inst.version)} | "
        f"`config/odoo{inst.major}.conf` | `.venv/odoo{inst.major}` |"
        for inst in cfg.instances()
    )
    venv_rows = "\n".join(
        f"| {inst.version} | {_readme_python((interpreters or {}).get(inst.version))} | "
        f"`{setuptools_requirement(inst.version)}` | "
        f"{_readme_requirement_changes(inst.version)} |"
        for inst in cfg.instances()
    )
    oca = ", ".join(cfg.oca_repos) if cfg.oca_repos else "(none)"
    # The language-server file only exists when OdooLS supports a version here.
    has_odools = bool(odools_versions(cfg))
    odools_line = (
        "\n├── odools.toml           # official Odoo language server profiles (Odoo >= 14)"
        if has_odools
        else ""
    )
    editor_hint = (
        " Install the recommended\nofficial Odoo extension (`Odoo.odoo`) and pick this workspace's profile for "
        "your version from the status\nbar (**Change Configuration**)."
        if has_odools
        else ""
    )
    return f"""# {cfg.name} — Odoo development workspace

Generated by **odoo_dwg**. This workspace hosts one Odoo Community instance per configured version, each with
its own virtualenv, config, and port. Odoo/OCA source lives in the shared cache at `{cfg.repos_dir}` and is
reused across workspaces.

## Versions

| Version | Instance | HTTP port | Config | Venv |
|---------|----------|-----------|--------|------|
{version_rows}

- OCA repositories: {oca}
- Custom addons: `addons-custom/` · OCA addons (symlinks): `addons-oca/`

## What each venv installs

| Version | Python | setuptools | Requirement changes |
|---------|--------|------------|---------------------|
{venv_rows}

`scripts/setup_venv.sh` rebuilds each venv the same way. Odoo ≤ 16 needs `setuptools<81` because it imports
`pkg_resources` at startup; Odoo ≤ 13 needs `setuptools<58` because `vatnumber` still uses `use_2to3`. A
requirement change replaces a deprecated project the branch still pins with its declared successor; the shared
clone is not modified. If a venv fails with `No module named 'pkg_resources'`, run
`.venv/odoo<major>/bin/pip install 'setuptools<81'`.

## Layout

```
{cfg.name}/
├── addons-custom/        # your modules
├── addons-oca/           # symlinks into the shared OCA cache
├── config/odoo<major>.conf
├── .venv/odoo<major>/    # one venv per version
├── scripts/              # setup_venv.sh, run-odoo<major>.sh
├── .vscode/              # tasks.json, launch.json, settings.json, extensions.json
├── workspace.json        # this workspace's profile — the manage flow reads it
├── README.md             # this file{odools_line}
└── {cfg.name}.code-workspace
```

## Setup & run

The venvs are already built. Create a database, then launch:

```bash
# From this workspace directory, on the Linux host:
createdb -h {cfg.db_host} -U {cfg.db_user} {cfg.name}    # once; the name F5 offers by default
bash scripts/run-odoo{cfg.instances()[0].major}.sh          # launch the {cfg.versions[0]} instance
```

Then open <http://{cfg.db_host}:{cfg.http_port_for(cfg.versions[0])}/web/login>. You can also create the database
from Odoo's own database manager at `/web/database/manager`; its master password is `admin`, set by
`admin_passwd` in each `config/odoo<major>.conf`. **`-h {cfg.db_host} -U {cfg.db_user}` is not optional**:
the development role is trusted over loopback TCP, not over the Unix socket, so a bare `createdb` fails with
`role "<your user>" does not exist`.

`bash scripts/setup_venv.sh` **re**builds every venv from scratch (the workspace was generated with them
built); run it after changing an interpreter or to repair one.

Mail goes nowhere outside this host: each `odoo.conf` points SMTP at `127.0.0.1:1025`. If the local capture
(Mailpit) is installed, read what Odoo sent at <http://localhost:8025>.

Each instance's `addons_path` is composed of `addons-custom`, the OCA repos, then the shared Odoo `addons`.
Open `{cfg.name}.code-workspace` in VSCode for tasks and debug launch configs.{editor_hint}

## Debugging (F5)

`.vscode/launch.json` has four configurations per version, all under the debugger:

| Configuration | Runs | Asks for |
|---|---|---|
| `Odoo <version>` | the server | — |
| `Odoo <version> shell` | `odoo-bin shell`: a Python REPL with `env` bound to a database | database |
| `Odoo <version> upgrade modules` | the server, upgrading modules on start (`-u`) | database, modules |
| `Odoo <version> test module` | one module's tests (`--test-enable --test-tags /<module>`), then stops | database, module |

The database prompt offers `{cfg.name}`. Breakpoints in your addons stop in all four, including in migration
scripts and tests. Odoo 12 runs tests only on a database created with demo data.

The shared Odoo clones are shallow (no history). For `git log`/`git blame` on the Odoo source, run
`git -C {cfg.repos_dir}/odoo-<version> fetch --unshallow` once.
"""


# --- migration (F3) --------------------------------------------------------


# Overrides applied via ``uv pip install --overrides``: an entry replaces every
# requirement of the same package name during resolution (entries for packages the
# requirements never pull are ignored). Odoo branches 16/17/18 all pin
# gevent==21.8.0 for python_version == '3.10' (the Jammy assumption), but that
# release predates CPython 3.10 (no cp310 wheel) and its sdist no longer compiles
# under modern Cython. The official requirements' own pins for the 3.11 row —
# gevent==22.10.2 + greenlet==2.0.2 — ship cp310 wheels, so we lift to those.
_PY310_OVERRIDES = ("gevent==22.10.2", "greenlet==2.0.2")


#: The last major whose ``requirements.txt`` pins ``pyldap``. 12.0 pins
#: ``pyldap==2.4.28``; 13.0 already pins ``python-ldap==3.1.0``.
PYLDAP_LAST_MAJOR = 12

# `pyldap` was a temporary Python-3 fork of `python-ldap`. Its own PyPI page says
# so: "THIS FORK IS DEPRECATED. The pyldap fork was merged back into python-ldap,
# and released as python-ldap 3.0.0." 2.4.28's setup passes `-R` to the linker — a
# SunOS flag GCC rejects — so it cannot build on a current toolchain:
#     cc: error: unrecognized command-line option '-R'
# The replacement is not a choice this project made: it is the package the fork
# became, at the version Odoo itself moved to in 13.0.
# `--overrides` pins versions; it cannot rename a package. Adding python-ldap
# alone left pyldap==2.4.28 in the resolution and it failed to build exactly as
# before. The fork's own final release is the bridge: 3.0.0.post1 contains no
# code and only requires python-ldap.
_PYLDAP_OVERRIDE = [
    "# pyldap==2.4.28 passes '-R' to cc and cannot build. 3.0.0.post1 is the fork's",
    "# own last release, which only requires python-ldap — the package it became.",
    "pyldap==3.0.0.post1; sys_platform != 'win32'",
    "# and the version Odoo itself moved to in 13.0, rather than whatever is latest.",
    "python-ldap==3.1.0; sys_platform != 'win32'",
]


def render_migration_overrides(version: str, python: str | None = None) -> str:
    """Per-version requirements repair for old branches, fed to ``--overrides``.

    Only the Python-3.10 steps need repairs today (see ``_PY310_OVERRIDES``);
    other interpreters resolve their branch's pins to installable wheels/sdists
    (validated on WSL: Odoo 15 on 3.8, Odoo 18 on 3.12).

    ``python`` is the interpreter the step will actually run, which differs from
    the matrix recommendation when the operator pinned the step; the repair must
    follow the interpreter in use, not the default one."""
    if python is None:
        python, _method = migration_interpreter(version)
    lines = [
        f"# Generated by odoo_dwg — requirements overrides for Odoo {version}"
        f" (Python {python})."
    ]
    if python and python_tuple(python)[:2] == (3, 10):
        lines.append("# gevent==21.8.0 has no cp310 wheel; lift to the branch's own 3.11 pins.")
        lines.extend(_PY310_OVERRIDES)
    if odoo_major(version) <= PYLDAP_LAST_MAJOR:
        lines.extend(_PYLDAP_OVERRIDE)
    return "\n".join(lines) + "\n"


def render_migration_scaffold(module: str, version: str, findings: list) -> str:
    """An additive ``pre-migration.py`` stub for one module/step: openupgradelib
    import plus one commented TODO per candidate finding. Inert until a developer
    reviews it — the header says so. ``findings`` are ``analysis.Finding``."""
    lines = [
        f"# Generated by odoo_dwg staging for {module} -> Odoo {version}.",
        "# REVIEW REQUIRED: these are CANDIDATE findings from the OpenUpgrade",
        "# analysis files — confirm each one, then implement and uncomment.",
        "# This stub does nothing until you complete it.",
        "from openupgradelib import openupgrade",
        "",
    ]
    for finding in findings:
        record = finding.record
        what = "model" if record.kind == "removed_model" else "field"
        # The path comes from the operator's own module tree, which this tool did
        # not write: a file name may legally contain a newline, and this comment
        # is a line of a Python file OpenUpgrade *executes*. `repr` keeps it one
        # line whatever it holds.
        lines.append(
            f"# TODO {record.model}: {what} '{record.name}' removed in {version}"
            f" (seen at {finding.path!r}:{finding.line})"
        )
    lines += [
        "",
        "",
        "@openupgrade.migrate()",
        "def migrate(env, version):",
        "    pass  # TODO: implement the reviewed operations above",
    ]
    return "\n".join(lines) + "\n"


def render_migration_report(
    env: MigrationEnv,
    runs: list,
    logs: dict[str, str],
    decisions: dict[str, list] | None = None,
    open_items: list[tuple[str, str]] | None = None,
) -> str:
    """The report an operator works through after — or during — a chain.

    ``runs`` are `runlog.Run`, oldest first; ``logs`` is the summarised Odoo log
    per step of the latest run; ``decisions`` the firewall's answers inside each
    step's window; ``open_items`` what is still unresolved, which is the section
    the whole thing exists for.

    Nothing here says what a warning *means*. Level, logger and count are what
    the line carries; naming categories would be asserting something about
    OpenUpgrade that this project has not verified.
    """
    lines = [
        f"# Migration report — {env.source} → {env.target}",
        "",
        "Generated by odoo_dwg from the driver's own step log, each step's Odoo log, and the",
        "outbound firewall's journal. **A step that was skipped ran nothing this time**: its",
        "warnings are in the run that first performed it.",
        "",
    ]

    if open_items:
        lines += ["## Still open", ""]
        lines += [f"- **{what}** — {detail}" for what, detail in open_items]
        lines.append("")
    else:
        lines += ["## Still open", "", "Nothing. Every step of the latest run finished, and no step's",
                  "log holds an error.", ""]

    lines += ["## Runs", "", "| Run | Chain | Started | Outcome | Steps |", "| --- | --- | --- | --- | --- |"]
    for run in runs:
        done = sum(1 for step in run.steps if step.outcome in ("ok", "skip"))
        lines.append(
            f"| `{run.run}` | {run.chain or '—'} | {run.started} | {run.outcome} | "
            f"{done}/{len(run.steps)} |"
        )
    lines.append("")

    if not runs:
        lines += ["No run has been recorded yet: the driver writes one line per event as it goes.", ""]
        return "\n".join(lines) + "\n"

    latest = runs[-1]
    lines += [f"## Latest run (`{latest.run}`)", ""]
    for step in latest.steps:
        lines += [f"### Step {step.version} — {step.outcome}" + (f" (exit {step.code})" if step.code else ""), ""]
        lines.append(f"- started `{step.started or '—'}`, ended `{step.ended or '—'}`")
        if step.outcome == "skip":
            lines += ["- already checkpointed, so nothing ran this time", ""]
            continue

        entries = logs.get(step.version) or []
        if entries:
            lines += ["", "| Level | Logger | Count | First message |", "| --- | --- | --- | --- |"]
            lines += [
                f"| {entry.level} | `{entry.logger}` | {entry.count} | {entry.first[:160]} |"
                for entry in entries
            ]
        else:
            lines.append("- its log holds no error or warning")

        answers = (decisions or {}).get(step.version) or []
        if answers:
            lines += ["", "**The step reached outside its own machine:**", ""]
            lines += [
                f"- `{answer.action}` {answer.host} ×{answer.count} (rule `{answer.rule}`)"
                for answer in answers
            ]
        lines.append("")

    return "\n".join(lines) + "\n"


def render_staging_report(
    module: str,
    steps: list[tuple[str, str, list, str | None]],
    promoted: list[tuple[str, str]] | None = None,
) -> str:
    """The per-module staging report the developer works through. ``steps`` is
    ``(version, tool_log_text, findings, scaffold_path_or_None)`` per step; the
    tool's log is carried verbatim. States the boundary: staging is a prepared
    starting point, never a finished migration."""
    lines = [
        f"# Staging report — {module}",
        "",
        "Generated by odoo_dwg. **Staging is a prepared starting point: your review",
        "completes the migration.** Findings are candidates (name matches with the",
        "owning model present), not proof.",
        "",
        "Each stage directory is a throwaway git repository: `odoo-module-migrate`",
        "refuses to run outside one, so staging creates it and commits the",
        "pre-migration state into it. It is not yours and is not pushed anywhere.",
        "",
    ]
    for version, log_text, findings, scaffold in steps:
        # The tool's log is carried verbatim, so the fence has to be longer than
        # any run of backticks in it — otherwise the log ends the block early and
        # the rest of the report is read as markdown.
        body = log_text.rstrip() or "(no output captured)"
        fence = "```"
        while fence in body:
            fence += "`"
        lines += [f"## Step {version}", "", "### odoo-module-migrate output (verbatim)", fence]
        lines.append(body)
        lines += [fence, ""]
        if findings:
            lines.append("### Candidate findings (confirm each)")
            for finding in findings:
                record = finding.record
                what = "model" if record.kind == "removed_model" else "field"
                lines.append(
                    f"- `{record.model}` {what} `{record.name}` removed in {version}"
                    f" — seen at `{finding.path!r}:{finding.line}`"
                )
            lines.append("")
        else:
            lines += ["### Candidate findings", "None detected.", ""]
        if scaffold:
            lines += [f"Scaffold written: `{scaffold}` — review and complete it.", ""]
    if promoted:
        lines += [
            "## Promoted copy",
            "",
            "Your reviewed code lives outside this environment; this environment's copy is a working",
            "copy of it. Neither is authoritative — where they differ, you decide which is right.",
            "",
            "| Step | Environment vs promoted |",
            "| --- | --- |",
        ]
        lines += [f"| {version} | {state} |" for version, state in promoted]
        lines.append("")
    return "\n".join(lines) + "\n"


def render_migration_conf(env: MigrationEnv, version: str) -> str:
    """Per-step ``odoo.conf`` for a migration step (no HTTP — runs stop-after-init)."""
    lines = [
        "[options]",
        f"; Generated by odoo_dwg — OpenUpgrade step to Odoo {version}.",
        f"addons_path = {env.addons_path(version)}",
        "",
        f"db_host = {env.db_host}",
        f"db_port = {env.db_port}",
        f"db_user = {env.db_user}",
        "",
        "workers = 0",
        "max_cron_threads = 0",
        "",
        *_smtp_to_capture(),
    ]
    return "\n".join(lines) + "\n"


def _render_step_preconditions(env: MigrationEnv, version: str) -> str:
    """The step's own code must be on disk before it claims to migrate anything.

    Odoo neither fails nor says anything when ``--upgrade-path`` points at a
    directory that is not there: it simply finds no scripts, and the step would
    be checkpointed as migrated. A clone interrupted mid-way is enough, since
    generation skips a checkout directory that merely exists."""
    if env.uses_legacy_layout(version):
        # The fork *is* Odoo here, so a missing checkout already fails loudly on
        # its own addons_path; its scripts live inside each add-on.
        needed = [(env.openupgrade_clone_dir(version) / "addons", "the OpenUpgrade fork's add-ons")]
    else:
        needed = [
            (env.upgrade_scripts_dir(version), "the OpenUpgrade scripts"),
            (env.openupgrade_clone_dir(version) / "openupgrade_framework", "openupgrade_framework"),
        ]
    return "".join(
        f'  [ -d {shlex.quote(str(path))} ] || '
        f'die "{version}: {what} not found at {path} — regenerate the environment"\n'
        for path, what in needed
    )


def _native_step_command(env: MigrationEnv, version: str) -> str:
    """The command that upgrades the working database to one version.

    Two shapes, because OpenUpgrade changed layout at 14. From 14 the scripts sit
    under ``--upgrade-path`` and ``openupgrade_framework`` is loaded. Up to 13 they
    live inside each add-on and neither flag exists — that step runs the fork's own
    ``odoo-bin`` and depends entirely on the add-ons path reaching the fork's
    ``addons``. The path comes from the step's config file, which states it
    explicitly: an inherited or defaulted path that resolves to some other copy of
    Odoo's add-ons skips every add-on migration while the step still succeeds."""
    venv = env.venv_dir(version)
    conf = env.config_file(version)
    log = env.logs_dir / f"{version}.log"
    odoo_bin = env.odoo_bin(version)
    q = shlex.quote
    run = f'{q(f"{venv}/bin/python")} {q(str(odoo_bin))} -c {q(str(conf))} -d "$DB"'
    if env.uses_legacy_layout(version):
        return f"{run} --update all --stop-after-init --logfile={q(str(log))}"
    scripts = env.upgrade_scripts_dir(version)
    return (
        f"{run} --upgrade-path={q(str(scripts))} --update all --stop-after-init "
        f"--load=base,web,openupgrade_framework --logfile={q(str(log))}"
    )


def render_migration_constraints(version: str) -> str | None:
    """Build constraints for a step whose dependencies a current toolchain cannot
    build as pinned, or ``None`` when the step needs none.

    Distinct from the requirements overrides: those change *what* is installed,
    these constrain the environment packages are *built* with. The 13.0 branch
    needs it because ``vatnumber==1.2`` still calls ``use_2to3``, which setuptools
    removed in 58."""
    if odoo_major(version) > LEGACY_LAYOUT_MAX_MAJOR:
        return None
    return (
        f"# Generated by odoo_dwg — build constraints for Odoo {version}.\n"
        "# vatnumber==1.2 uses use_2to3, removed in setuptools 58.\n"
        "setuptools<58\n"
    )


def _render_preflight_host(env: MigrationEnv) -> str:
    """Bash host-scope preflight: chain tools, PostgreSQL, dump integrity. The
    bash mirror of ``preflight.gather_host_facts`` (see design: the driver must
    stay plain bash, so the checks are rendered, kept in this one function)."""
    lines = [
        "preflight_host() {",
        '  command -v uv >/dev/null 2>&1 || fail "uv not found (needed for the native venvs)"',
    ]
    lines += [
        # -X, like every other psql this project runs: `~/.psqlrc` can hold a
        # `\\c otherdb` or a `\\! command`, none of which is visible in the plan.
        '  psql -X -tAc "SELECT 1" postgres >/dev/null 2>&1 || fail "PostgreSQL not reachable as $PGUSER@$PGHOST:$PGPORT"',
        '  [ -r "$SRC_DUMP" ] || fail "source dump not readable: $SRC_DUMP"',
        '  pg_restore --list "$SRC_DUMP" >/dev/null 2>&1 || fail "pg_restore cannot list $SRC_DUMP — a custom-format dump (pg_dump -Fc) is required"',
        '  echo "[preflight] host checks passed"',
        "}",
    ]
    return "\n".join(lines)


def _render_coverage_helper() -> str:
    """The bash+python helper the driver uses to judge one step's coverage.

    It applies the same rule as ``preflight.gather_coverage``: resolve what
    OpenUpgrade declares renamed or merged before calling anything missing, then
    split what is left by author — Odoo's own dropped code is a warning the
    upgrade handles, anybody else's is the operator's to supply. It reads
    ``apriori.py`` with ``ast`` at run time (never executing it), which is why
    nothing here needs the checkout at render time.

    Exits non-zero only when the blocking class is non-empty.
    """
    return "\n".join(
        [
            "coverage_step() {",
            '  local version="$1" apriori="$2" customdir="$3"; shift 3',
            # The module list travels in the environment, never on stdin: the
            # heredoc below *is* python's stdin, so anything piped in is lost and
            # the check would silently pass with nothing to check.
            "  python3 - \"$version\" \"$apriori\" \"$customdir\" \"$@\" <<'PYCOV'",
            "import ast, os, sys",
            "version, apriori, customdir, *sources = sys.argv[1:]",
            '# Exact spellings only: OCA authors contain "Odoo" and must not pass.',
            'ODOO_AUTHORS = {"odoo s.a.", "odoo sa", "openerp s.a.", "openerp sa", "odoo"}',
            "renames = {}",
            "try:",
            '    tree = ast.parse(open(apriori, encoding="utf-8").read())',
            "except (OSError, ValueError, SyntaxError):",
            '    print("[coverage] %s: no readable apriori.py — renames unknown" % version,',
            "          file=sys.stderr)",
            "    tree = None",
            "if tree is not None:",
            "    for node in tree.body:",
            "        if not isinstance(node, ast.Assign):",
            "            continue",
            "        names = {t.id for t in node.targets if isinstance(t, ast.Name)}",
            '        if not names & {"renamed_modules", "merged_modules"}:',
            "            continue",
            "        try:",
            "            value = ast.literal_eval(node.value)",
            "        except (ValueError, TypeError):",
            "            continue",
            "        if isinstance(value, dict):",
            "            renames.update({str(k): str(v) for k, v in value.items()",
            "                            if isinstance(v, str)})",
            "def resolves(name):",
            "    return any(os.path.isdir(os.path.join(src, name)) for src in sources)",
            "",
            "# Nothing to resolve against: report that, rather than calling every",
            "# module missing — including `base`, which cannot be dropped.",
            "if not any(os.path.isdir(src) for src in sources):",
            "    print('[coverage] %s: its sources are not on disk — regenerate the"
            " environment' % version, file=sys.stderr)",
            "    raise SystemExit(1)",
            "blocking, dropped = [], []",
            'modules_tsv = os.environ.get("ODWG_MODULES_TSV", "")',
            "if not modules_tsv.strip():",
            '    print("[coverage] %s: no module list to check" % version, file=sys.stderr)',
            "    sys.exit(1)",
            "for line in modules_tsv.splitlines():",
            '    name, _, author = line.strip().partition("\\t")',
            "    if not name or resolves(name):",
            "        continue",
            "    successor = renames.get(name)",
            "    if successor and resolves(successor):",
            "        continue",
            "    if author.strip().lower() in ODOO_AUTHORS:",
            "        dropped.append(name)",
            "    else:",
            "        blocking.append(name)",
            "for name in dropped:",
            '    print("[coverage] %s is not in %s and is not renamed — Odoo dropped it; '
            'OpenUpgrade removes it" % (name, version), file=sys.stderr)',
            "for name in blocking:",
            '    print("[coverage] %s missing for %s — place it in %s" % (name, version, customdir),',
            "          file=sys.stderr)",
            "sys.exit(1 if blocking else 0)",
            "PYCOV",
            "}",
        ]
    )


def _render_preflight_db(env: MigrationEnv) -> str:
    """Bash database-scope preflight, run right after the fresh 00_source restore
    (a resumed database is mid-chain, so the version check only holds there):
    declared-source match from ir_module_module, then per-step addons coverage.

    Coverage asks for each module's author as well as its name, because that is
    what separates a core module Odoo dropped (the upgrade removes it) from code
    the step genuinely needs."""
    source_major = odoo_major(env.source)
    lines = [
        _render_coverage_helper(),
        "",
        "preflight_db() {",
        "  local base_ver blocking=0",
        '  base_ver=$(psql -X -d "$DB" -tAc "SELECT latest_version FROM ir_module_module WHERE name=\'base\'") '
        '|| fail "could not query the restored database \'$DB\'"',
        f'  case "$base_ver" in {source_major}.*) ;; *) fail "database base version \'$base_ver\' does not match declared source {env.source}";; esac',
        '  modules_tsv=$(psql -X -d "$DB" -tAc "SELECT name || E\'\\t\' || coalesce(author, \'\') FROM ir_module_module WHERE state=\'installed\' ORDER BY name") '
        '|| fail "could not list the installed modules of \'$DB\'"',
    ]
    for version in env.chain():
        # The step's own add-ons path, so coverage asks exactly what the step
        # will be able to resolve — including the <= 13 fork layout.
        sources = " ".join(shlex.quote(str(p)) for p in env.coverage_dirs(version))
        apriori = shlex.quote(str(env.apriori_file(version)))
        custom = shlex.quote(str(env.addons_custom_dir(version)))
        lines += [
            f"  # coverage: step {version}",
            f'  ODWG_MODULES_TSV="$modules_tsv" coverage_step {version} {apriori} {custom} '
            f"{sources} || blocking=1",
        ]
    lines += [
        '  [ "$blocking" = 0 ] || fail "addons coverage incomplete (see [coverage] lines above)"',
        '  echo "[preflight] database checks passed"',
        "}",
    ]
    return "\n".join(lines)


def render_run_migration_sh(env: MigrationEnv) -> str:
    """The checkpointing driver: preflight the host, restore a source dump into a
    working DB (verifying it before step 1), then run each step in order, dumping
    a checkpoint after each success (never touches the source/production database).

    A re-run resumes from the last good step: the working DB is restored from the
    newest checkpoint before the first pending step, because a failed step leaves
    it half-migrated (OpenUpgrade commits module by module). The run is bound to
    one source dump by its SHA-256, so a different dump is refused instead of
    silently ignored."""
    header = f"""#!/usr/bin/env bash
# Generated by odoo_dwg — OpenUpgrade migration {env.source} -> {env.target}.
set -euo pipefail

SRC_DUMP="${{1:?usage: run_migration.sh <source-db-custom-format-dump>}}"
DB={shlex.quote(env.database)}
export PGHOST={shlex.quote(env.db_host)} PGPORT={int(env.db_port)} PGUSER={shlex.quote(env.db_user)}
CK={shlex.quote(str(env.checkpoints_dir))}
LOGS={shlex.quote(str(env.logs_dir))}
# A checkpoint is a dump of the restored copy of a customer's production
# database, and a log is Odoo's log for it: neither is for other accounts on this
# host to read, whatever the operator's umask and home directory allow.
umask 077
mkdir -p "$CK" "$LOGS"
chmod 700 "$CK" "$LOGS"

fail() {{ echo "[preflight-fail] $1" >&2; exit 1; }}
die() {{ echo "[fail] $1" >&2; exit 1; }}

{_render_preflight_host(env)}

{_render_preflight_db(env)}

# One line per event, appended and never rewritten: a run killed mid-step still
# leaves a readable record, and a watcher can tail it while the chain runs. The
# timestamp is what `journalctl --since/--until` takes, so a step's window can be
# handed to the firewall's journal without guessing where the step began.
#   <when>\t<run>\t<step>\t<event>\t<detail>
STEPS="$LOGS/steps.tsv"
mark() {{ printf '%s\t%s\t%s\t%s\t%s\n' "$(date -Is)" "${{SRC_SHA:0:12}}" "$1" "$2" "${{3:-}}" >> "$STEPS"; }}

have_ck() {{ [ -f "$CK/$1.dump" ]; }}
# Written through a temp file: an interrupted dump must never look like a
# finished checkpoint the next run would trust.
checkpoint() {{
  # Explicitly, not as a && b || c: a failing pg_dump must abort the run instead
  # of leaving an empty .tmp behind while the step reports success.
  if ! pg_dump -Fc "$DB" > "$CK/$1.dump.tmp"; then
    rm -f "$CK/$1.dump.tmp"
    die "checkpoint $1 could not be written"
  fi
  mv "$CK/$1.dump.tmp" "$CK/$1.dump" || die "checkpoint $1 could not be saved"
  echo "[checkpoint] $1"
}}

preflight_host

restore_ck() {{
  echo "[init] restoring checkpoint $1 into working DB '$DB'"
  dropdb --if-exists "$DB"
  createdb "$DB"
  pg_restore --no-owner --dbname "$DB" "$CK/$1.dump"
}}

SRC_SHA=$(sha256sum "$SRC_DUMP" | cut -d' ' -f1)
mark - run-start "{env.source} -> {env.target}"
if ! have_ck 00_source; then
  # A fresh run owns the checkpoint directory: step dumps left by an earlier run
  # belong to another attempt and would be skipped as if they were this one's.
  rm -f "$CK"/*.dump "$CK"/*.dump.tmp "$CK/source.sha256"
  mark - restore 00_source
  echo "[init] restoring source dump into working DB '$DB'"
  dropdb --if-exists "$DB"
  createdb "$DB"
  pg_restore --no-owner --dbname "$DB" "$SRC_DUMP"
  preflight_db
  echo "$SRC_SHA" > "$CK/source.sha256.tmp" && mv "$CK/source.sha256.tmp" "$CK/source.sha256"
  checkpoint 00_source
else
  # Three states, not two: recorded and equal, recorded and different, or not
  # recorded at all. Calling the third one "another source dump" was false, and
  # the remedy it named threw away every completed step of the chain.
  CK_SHA=$(cat "$CK/source.sha256" 2>/dev/null || true)
  if [ -z "$CK_SHA" ]; then
    die "the checkpoints in $CK do not record which dump they came from.
  If they came from $SRC_DUMP, adopt them with:
    sha256sum \\"$SRC_DUMP\\" | cut -d' ' -f1 > \\"$CK/source.sha256\\"
  If they came from another dump, remove $CK to start over."
  elif [ "$CK_SHA" != "$SRC_SHA" ]; then
    die "checkpoints in $CK came from another source dump — remove that whole directory to start over"
  fi
  # A failed step leaves the working DB half-migrated: resume from the newest
  # checkpoint, not from whatever the DB holds now.
  LAST=00_source
  gap=0
  for step in {' '.join(env.chain())}; do
    if [ "$gap" = 0 ] && have_ck "$step"; then
      LAST="$step"
    else
      # Past the first gap nothing is trustworthy: those dumps came from another
      # attempt, and a step after a gap would run on the wrong database.
      gap=1
      rm -f "$CK/$step.dump"
    fi
  done
  if [ "$LAST" = "{env.target}" ]; then
    echo "[init] every step already has a checkpoint"
  else
    mark - restore "$LAST"
    restore_ck "$LAST"
  fi
fi
"""
    steps: list[str] = []
    for version in env.chain():
        layout = "legacy layout" if env.uses_legacy_layout(version) else "upgrade-path layout"
        steps.append(
            f"""
# --- step: upgrade to {version} ({layout}) ---
if have_ck "{version}"; then
  echo "[skip] {version} already migrated"
  mark "{version}" skip
else
  echo "[step] upgrading to {version} ({layout})"
  mark "{version}" start
{_render_step_preconditions(env, version)}  code=0
  {_native_step_command(env, version)} || code=$?
  # `|| code=$?`, not `if ! cmd; then code=$?`: inside the negation `$?` is the
  # status of *not having failed*, which is 0, so every failure was recorded as
  # exit 0 — verified by running the driver against a failing step.
  if [ "$code" -ne 0 ]; then
    mark "{version}" fail "$code"
    die "step {version} failed — see {env.logs_dir}/{version}.log"
  fi
  checkpoint "{version}"
  mark "{version}" ok
fi"""
        )
    footer = (
        '\n\nmark - run-ok\n'
        f'echo "[done] migration complete — working DB is now Odoo {env.target}"\n'
    )
    return header + "".join(steps) + footer


def render_tester_module(probes: list, uncovered: list[str], chain: str) -> dict[str, str]:
    """The rehearsal tester add-on, as ``relative path -> content``.

    Declaration-only by design: it depends on ``base`` alone and refers to no
    subject in code, so it installs on the source version whatever the chain
    contains. What it carries is one row per probe.
    """
    return {
        "__init__.py": "from . import models\n",
        "models/__init__.py": "from . import probe\n",
        "models/probe.py": _render_probe_model(),
        "security/ir.model.access.csv": (
            "id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink\n"
            f"access_{tester.PROBE_TABLE},{tester.PROBE_MODEL},"
            f"model_{tester.PROBE_TABLE},,1,0,0,0\n"
        ),
        "data/probes.xml": _render_probe_data(probes),
        "__manifest__.py": _render_tester_manifest(probes, uncovered, chain),
    }


def _render_probe_model() -> str:
    """Written for Odoo 12 to 19 alike: `from odoo import fields, models`, a
    `_description`, and no field type that arrived mid-chain."""
    return (
        "# Generated by odoo_dwg. Rehearsal instrument — see the manifest.\n"
        "from odoo import fields, models\n"
        "\n"
        "\n"
        "class MigrationProbe(models.Model):\n"
        f"    _name = {tester.PROBE_MODEL!r}\n"
        '    _description = "odoo_dwg migration probe"\n'
        "\n"
        "    name = fields.Char(required=True, index=True)\n"
        "    kind = fields.Char(required=True)\n"
        "    step = fields.Char(required=True)\n"
        "    subject_model = fields.Char(required=True)\n"
        "    subject_field = fields.Char()\n"
        "    expected_gone = fields.Boolean()\n"
        "    source_line = fields.Text()\n"
    )


def _render_probe_data(probes: list) -> str:
    """One record per probe. `noupdate` so a step's `-u all` cannot rewrite what
    the source version recorded — the record is the evidence."""
    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        "<!-- Generated by odoo_dwg. One record per declared expectation. -->",
        "<odoo>",
        '  <data noupdate="1">',
    ]
    for probe in probes:
        lines += [
            f'    <record id="{escape(probe.name)}" model="{tester.PROBE_MODEL}">',
            f'      <field name="name">{escape(probe.name)}</field>',
            f'      <field name="kind">{escape(probe.kind)}</field>',
            f'      <field name="step">{escape(probe.version)}</field>',
            f'      <field name="subject_model">{escape(probe.model)}</field>',
            f'      <field name="subject_field">{escape(probe.field)}</field>',
            f'      <field name="expected_gone" '
            f'eval="{"True" if probe.expected_gone else "False"}"/>',
            # The analysis file's own words: a probe that paraphrased its source
            # would make its own claim unverifiable.
            # Tabs out: the check reads these rows tab-separated, and an
            # analysis line holding one would split into a probe that is not there.
            f'      <field name="source_line">'
            f'{escape(probe.detail.replace(chr(9), " "))}</field>',
            "    </record>",
        ]
    lines += ["  </data>", "</odoo>", ""]
    return "\n".join(lines)


def _render_tester_manifest(probes: list, uncovered: list[str], chain: str) -> str:
    """No menu, no group, no `auto_install`: installing it by accident changes
    nothing a user sees."""
    covered = sorted({probe.kind for probe in probes})
    summary = (
        f"odoo_dwg rehearsal instrument for the {chain} chain — declares what the "
        "OpenUpgrade sources predict, so a step can be asked what it took away. "
        "Not for a production database."
    )
    description = "\n".join(
        [
            f"Generated by odoo_dwg for the {chain} chain.",
            "",
            "Each record of odwg.migration.probe names one upstream subject, the class of",
            "change its step's analysis file declares, and that file's own line.",
            "",
            f"Classes covered ({len(covered)}): " + ", ".join(covered) or "none",
            f"Classes this chain never exercises ({len(uncovered)}): "
            + (", ".join(uncovered) or "none"),
        ]
    )
    return (
        "# Generated by odoo_dwg. Regenerate rather than edit.\n"
        "{\n"
        f'    "name": "odoo_dwg migration tester ({chain})",\n'
        '    "version": "1.0.0",\n'
        '    "category": "Technical",\n'
        '    "license": "LGPL-3",\n'
        f'    "summary": {summary!r},\n'
        f'    "description": """{description}""",\n'
        '    "depends": ["base"],\n'
        '    "data": ["security/ir.model.access.csv", "data/probes.xml"],\n'
        '    "installable": True,\n'
        '    "application": False,\n'
        "}\n"
    )


def render_seed_conf(env: MigrationEnv) -> str:
    """``odoo.conf`` for the source version a demo seed is built on.

    Plain Odoo, not an OpenUpgrade step: the add-ons path is the source's own
    (`source_addons_path`), and mail goes to the local capture like every other
    config this tool writes — demo data contains addresses.
    """
    return "\n".join(
        [
            "[options]",
            f"; Generated by odoo_dwg — demo seed for Odoo {env.source}.",
            f"addons_path = {env.source_addons_path}",
            "",
            f"db_host = {env.db_host}",
            f"db_port = {env.db_port}",
            f"db_user = {env.db_user}",
            "",
            "workers = 0",
            "max_cron_threads = 0",
            "",
            *_smtp_to_capture(),
        ]
    ) + "\n"


def render_seed_demo_sh(env: MigrationEnv, modules: list[str]) -> str:
    """Build a demo database at the source version and dump it for the driver.

    Installed one module at a time, not in one ``-i a,b,c``: Odoo stops at the
    first failure and reports it, and with a single call the operator is told
    only that *something* did not install. One at a time names which — and the
    script stops there rather than dumping a database missing a module the
    rehearsal was meant to exercise.

    The demo flag is **not** passed, and that is the verified answer rather than
    an omission. In 12.0 to 18.0 `--without-demo` carries `my_default=False`
    (`odoo/tools/config.py`), so a database created with `-i` gets Odoo's demo
    data unless the flag disables it. 19.0 rewrote the option — `dest="with_demo"`,
    `type='without_demo'`, and its help now reads "don't install demo data in new
    databases (default)" — so there the default is the opposite. A chain's source
    is always <= 18.0 (`migration_chain` requires source < target <= 19.0), so
    omitting the flag is right for every source this tool accepts; a 19.0 source
    would have to ask for demo data explicitly, and cannot occur.
    """
    q = shlex.quote
    venv = env.venv_dir(env.source)
    odoo_bin = env.odoo_bin(env.source)
    conf = env.config_file(env.source)
    log = env.logs_dir / f"seed-{env.source}.log"
    database = env.source_database
    dump = env.source_dump_file
    run = f'{q(f"{venv}/bin/python")} {q(str(odoo_bin))} -c {q(str(conf))} -d {q(database)}'
    lines = [
        "#!/bin/bash",
        "# Generated by odoo_dwg. Builds a demo source database and dumps it.",
        "set -euo pipefail",
        "",
        'die() { echo "[fail] $*" >&2; exit 1; }',
        "",
        f'DB={q(database)}',
        f'DUMP={q(str(dump))}',
        f'LOG={q(str(log))}',
        "",
        '[ -x "$(command -v createdb)" ] || die "createdb not on PATH"',
        f'[ -x {q(f"{venv}/bin/python")} ] || die "no venv for Odoo {env.source}: generate the environment first"',
        f'[ -r {q(str(odoo_bin))} ] || die "no Odoo {env.source} clone: generate the environment first"',
        "",
        '# A dump the driver may already have checkpoints against is not replaced',
        '# silently; the caller confirms and removes it.',
        '[ -e "$DUMP" ] && die "$DUMP exists — remove it to seed again"',
        "",
        'if psql -X -w -lqt | cut -d\\| -f1 | grep -qw "$DB"; then',
        '  die "database $DB exists — drop it to seed again"',
        "fi",
        'echo "[init] creating $DB"',
        f'createdb -h {q(env.db_host)} -p {int(env.db_port)} -U {q(env.db_user)} "$DB"',
        "",
        # `base` with demo data first: the flag is only read when the database is
        # initialised, so every later module inherits the demo set.
        'echo "[step] installing base with demo data"',
        f'{run} -i base --stop-after-init --logfile="$LOG" '
        '|| die "base did not install — see $LOG"',
    ]
    for module in modules:
        lines += [
            f'echo "[step] installing {module}"',
            f'{run} -i {q(module)} --stop-after-init --logfile="$LOG" '
            f'|| die "{module} did not install — see $LOG"',
        ]
    lines += [
        "",
        'echo "[step] dumping $DB"',
        # -Fc: the format run_migration.sh requires, and the one it checks for.
        # Written beside the target and renamed: a dump interrupted halfway is not
        # a dump, and one left under the real name would be taken for one by the
        # next seed and by the driver.
        f'pg_dump -h {q(env.db_host)} -p {int(env.db_port)} -U {q(env.db_user)} '
        '-Fc -f "$DUMP.tmp" "$DB" || { rm -f "$DUMP.tmp"; die "pg_dump failed"; }',
        'mv -f "$DUMP.tmp" "$DUMP"',
        'echo "[done] $DUMP"',
        'echo "Run the chain with: ./run_migration.sh $DUMP"',
        "",
    ]
    return "\n".join(lines)
