"""Pure text builders for every generated workspace artifact.

Standard-library only, no I/O: each function returns the exact file *content* as a
string, so tests can assert on the rendered text and planners can wrap it in a
``write_text_file_command``. All generated artifacts are **English** (they are
technical and portable); the app's own UI is what gets translated, not these.

Odoo config keys, ``addons_path`` composition, and the source-install flow are
anchored to the official Odoo "Source install" and CLI / ``odoo.conf`` reference
pages (see docs/).
"""

from __future__ import annotations

import json
import shlex
from importlib import resources
from pathlib import Path
from xml.sax.saxutils import escape

from . import egress, neutralise, tester
from .models import (
    LEGACY_LAYOUT_MAX_MAJOR,
    UV_PYTHON,
    InstanceConfig,
    InterpreterChoice,
    MigrationEnv,
    WorkspaceConfig,
    migration_interpreter,
    odoo_major,
    python_tuple,
    requirement_substitute,
    setuptools_requirement,
    version_support,
)


def _gevent_port_key(version: str) -> str:
    """Live-chat/bus port key: ``gevent_port`` on Odoo ≥ 16, else ``longpolling_port``."""
    return "gevent_port" if odoo_major(version) >= 16 else "longpolling_port"


def _smtp_to_capture() -> list[str]:
    """Outgoing mail goes to the local capture (Mailpit): shown there when it runs,
    refused when it does not — never delivered. A mail server stored in the
    database takes precedence over these keys; see the mail redirect action."""
    return [
        "; Mail goes to the local capture (Mailpit); never delivered. docs/host/egress-control.md",
        f"smtp_server = {egress.MAILPIT_SMTP_HOST}",
        f"smtp_port = {egress.MAILPIT_SMTP_PORT}",
    ]


def render_odoo_conf(cfg: WorkspaceConfig, version: str) -> str:
    """Render a development ``odoo.conf`` for one instance of the workspace.

    Development posture: ``workers = 0`` (threaded, debugger-friendly), the
    composed ``addons_path``, the derived per-version HTTP port, and a separate
    bus port. Keys are the official ``odoo.conf`` options.
    """
    http_port = cfg.http_port_for(version)
    bus_port = http_port + 1000
    lines = [
        "[options]",
        "; Generated by odoo_dwg — development configuration.",
        f"addons_path = {cfg.addons_path(version)}",
        "",
        "http_interface = 127.0.0.1",
        f"http_port = {http_port}",
        f"{_gevent_port_key(version)} = {bus_port}",
        "",
        "; Development posture: threaded mode so the debugger can attach.",
        "workers = 0",
        "max_cron_threads = 1",
        # No `reload`: it re-executes the process as soon as watchdog is
        # installed, which detaches the debugger every launch config attaches.
        "dev_mode = qweb,xml",
        "",
        f"db_host = {cfg.db_host}",
        f"db_port = {cfg.db_port}",
        f"db_user = {cfg.db_user}",
        "admin_passwd = admin",
        "",
        *_smtp_to_capture(),
    ]
    return "\n".join(lines) + "\n"


def requirements_install_command(pip: str, requirements: str, version: str) -> str:
    """``pip install -r`` of a branch's requirements, with any substitute applied:
    the dropped project's line is filtered out and its replacement installed in
    the same resolution (see ``models.REQUIREMENT_SUBSTITUTES``)."""
    substitute = requirement_substitute(version)
    if substitute is None:
        return f"{shlex.quote(pip)} install -r {shlex.quote(requirements)}"
    dropped, replacement = substitute
    pattern = shlex.quote(f"^{dropped}([=<>!~; ]|$)")
    return (
        # pipefail: without it only pip's status is seen, so an unreadable
        # requirements file would install the substitute alone and report [OK].
        f"set -o pipefail && grep -v -i -E {pattern} {shlex.quote(requirements)} | "
        f"{shlex.quote(pip)} install -r /dev/stdin {shlex.quote(replacement)}"
    )


def render_setup_venv_sh(
    cfg: WorkspaceConfig,
    interpreters: dict[str, InterpreterChoice] | None = None,
) -> str:
    """A reproducible bash script that (re)builds every instance venv and installs
    its version-matched requirements from the shared repo cache.

    ``interpreters`` must be the same resolved choices the generation plan used:
    a version whose venv the plan builds with a ``uv``-provided interpreter has to
    be rebuilt the same way here, or re-running this script would quietly replace
    it with the host ``python3`` — the exact breakage the support matrix exists to
    prevent."""
    header = [
        "#!/usr/bin/env bash",
        "# Generated by odoo_dwg — create/refresh the per-version virtualenvs.",
        "set -euo pipefail",
        "",
    ]
    blocks: list[str] = []
    for inst in cfg.instances():
        venv = cfg.venv_dir(inst.version)
        odoo = cfg.odoo_clone_dir(inst.version)
        choice = (interpreters or {}).get(inst.version)
        if choice and choice.source == UV_PYTHON and choice.python:
            create = [
                f'# Odoo {inst.version} supports Python {version_support(inst.version).python_range_text()}',
                f"uv venv --seed --no-project --python {shlex.quote(choice.python)} "
                f"{shlex.quote(str(venv))}",
            ]
        else:
            create = [f"python3 -m venv {shlex.quote(str(venv))}"]
        marker = cfg.venv_ready_marker(inst.version)
        blocks.append(
            "\n".join(
                [
                    f"echo {shlex.quote(f'[odoo{inst.major}] creating venv {venv}')}",
                    # Clear the ready marker first and write it last: neither
                    # `uv venv --seed` nor `python3 -m venv` removes it, so a run
                    # that dies between them would leave a half-built venv wearing
                    # the marker that tells every later flow to skip it.
                    f"rm -f {shlex.quote(str(marker))}",
                    *create,
                    f"{shlex.quote(f'{venv}/bin/pip')} install --upgrade pip wheel "
                    f"{shlex.quote(setuptools_requirement(inst.version))}",
                    requirements_install_command(
                        f"{venv}/bin/pip", f"{odoo}/requirements.txt", inst.version
                    ),
                    f"touch {shlex.quote(str(marker))}",
                    "",
                ]
            )
        )
    return "\n".join(header + blocks)


def render_run_sh(cfg: WorkspaceConfig, version: str) -> str:
    """A bash launcher for one instance (venv python + odoo-bin + its conf)."""
    inst = InstanceConfig(cfg.name, version)
    venv = cfg.venv_dir(version)
    odoo = cfg.odoo_clone_dir(version)
    conf = cfg.config_file(version)
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# Generated by odoo_dwg — run the {inst.name} instance.",
            "set -euo pipefail",
            f"exec {shlex.quote(f'{venv}/bin/python')} {shlex.quote(f'{odoo}/odoo-bin')} "
            f'-c {shlex.quote(str(conf))} "$@"',
            "",
        ]
    )


def render_vscode_settings(cfg: WorkspaceConfig) -> str:
    default = cfg.versions[0]
    settings = {
        "python.defaultInterpreterPath": str(cfg.venv_dir(default) / "bin" / "python"),
        "python.terminal.activateEnvironment": True,
        # The official Odoo language server analyses Python; Pylance doing the
        # same would duplicate (and contradict) its diagnostics. The Python
        # extension stays for debugging and interpreter selection.
        "python.languageServer": "None",
        "files.exclude": {"**/__pycache__": True, "**/*.pyc": True},
        "search.exclude": {"**/.venv": True, "**/.repos": True},
    }
    return json.dumps(settings, indent=2) + "\n"


# The official Odoo extension and the language server it runs (odoo/odoo-vscode,
# odoo/odoo-ls). See docs/workspace/editor.md for the update procedure.
ODOO_EXTENSION_ID = "Odoo.odoo"

# The OdooLS release this configuration was last reviewed against. Bump it in
# the change that adopts what a review of newer releases found, never alone:
# tools/verify_odools_config.py reports the release notes since this version.
ODOOLS_REVIEWED_VERSION = "1.4.0"

# The only keys emitted per profile: the "minimal config file" of the OdooLS
# documentation. The schema is strict (additionalProperties: false), so an
# unknown key breaks the whole file; these four are in every stable schema on
# record. Keys documented as applying from a given release (the 1.5 JavaScript
# options, semantic-token switches) and template variables are deliberately
# never emitted — they are exactly what changes between releases.
ODOOLS_KEYS: tuple[str, ...] = ("name", "odoo_path", "addons_paths", "python_path")

# OdooLS refuses Odoo below this major ("only supports version 14 and above").
ODOOLS_MIN_ODOO_MAJOR = 14


def odools_versions(cfg: WorkspaceConfig) -> list[str]:
    """The workspace versions the official language server can open."""
    return [v for v in cfg.versions if odoo_major(v) >= ODOOLS_MIN_ODOO_MAJOR]


def _toml_string(value: str) -> str:
    """A TOML basic string. JSON's string escaping is a valid subset of TOML's
    (backslash, quote, control characters, \\uXXXX), so it quotes paths safely."""
    return json.dumps(value, ensure_ascii=False)


def render_odools_toml(cfg: WorkspaceConfig) -> str:
    """The official Odoo language server's configuration: one profile per version.

    The workspace opens only its own root while Odoo lives in the shared cache
    outside it — often in several versions — so OdooLS's zero-config detection
    cannot find it. Each profile states the four facts the generator already
    knows, as absolute paths. Core add-ons are loaded by OdooLS from
    ``odoo_path``, so ``addons_paths`` lists the workspace's own directories only."""
    lines = [
        "# Generated by odoo_dwg — profiles for the official Odoo language server",
        f"# (OdooLS, reviewed against {ODOOLS_REVIEWED_VERSION}). Pick one from the status bar.",
        "# Only the documented minimal keys are set; add your own below if you need more.",
    ]
    skipped = [v for v in cfg.versions if v not in odools_versions(cfg)]
    if skipped:
        lines.append(
            f"# No profile for {', '.join(skipped)}: OdooLS supports Odoo "
            f"{ODOOLS_MIN_ODOO_MAJOR} and above only."
        )
    for inst in cfg.instances():
        if inst.version not in odools_versions(cfg):
            continue
        addons = ", ".join(
            _toml_string(str(path)) for path in cfg.addons_dirs(inst.version, include_core=False)
        )
        values = {
            "name": _toml_string(f"{cfg.name} {inst.version}"),
            "odoo_path": _toml_string(str(cfg.odoo_clone_dir(inst.version))),
            "addons_paths": f"[{addons}]",
            "python_path": _toml_string(str(cfg.venv_dir(inst.version) / "bin" / "python")),
        }
        lines += ["", "[[config]]"] + [f"{key} = {values[key]}" for key in ODOOLS_KEYS]
    return "\n".join(lines) + "\n"


def render_vscode_extensions() -> str:
    recommendations = {
        "recommendations": [
            "ms-python.python",
            "ms-python.debugpy",
            ODOO_EXTENSION_ID,
        ]
    }
    return json.dumps(recommendations, indent=2) + "\n"


def render_vscode_tasks(cfg: WorkspaceConfig) -> str:
    tasks = {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Setup venvs",
                "type": "shell",
                "command": "bash scripts/setup_venv.sh",
                "problemMatcher": [],
            }
        ]
        + [
            {
                "label": f"Run odoo{odoo_major(v)}",
                "type": "shell",
                "command": f"bash scripts/run-odoo{odoo_major(v)}.sh",
                "problemMatcher": [],
            }
            for v in cfg.versions
        ],
    }
    return json.dumps(tasks, indent=2) + "\n"


# Debug entry points per version, beyond serving: Odoo's interactive shell, a
# server that upgrades modules on start, and one module's tests. Each asks what
# it needs at launch through the ``inputs`` below (``${input:<id>}``).
LAUNCH_INPUT_DATABASE = "odooDatabase"
LAUNCH_INPUT_MODULES = "odooModules"
LAUNCH_INPUT_TEST_MODULE = "odooTestModule"


def _launch_inputs(cfg: WorkspaceConfig) -> list[dict]:
    return [
        {
            "id": LAUNCH_INPUT_DATABASE,
            "type": "promptString",
            "description": "Odoo database",
            "default": cfg.name,
        },
        {
            "id": LAUNCH_INPUT_MODULES,
            "type": "promptString",
            "description": "Modules to upgrade (comma-separated)",
        },
        {
            "id": LAUNCH_INPUT_TEST_MODULE,
            "type": "promptString",
            "description": "Module whose tests to run",
        },
    ]


def _launch_configuration(cfg: WorkspaceConfig, version: str, name: str, args: list[str]) -> dict:
    return {
        "name": name,
        "type": "debugpy",
        "request": "launch",
        "python": str(cfg.venv_dir(version) / "bin" / "python"),
        "program": str(cfg.odoo_clone_dir(version) / "odoo-bin"),
        "args": args,
        "console": "integratedTerminal",
        "justMyCode": False,
    }


def render_vscode_launch(cfg: WorkspaceConfig) -> str:
    """Four debug configurations per version: serve, shell, upgrade modules and
    test one module. All run ``odoo-bin`` from the version's venv under debugpy."""
    database = f"${{input:{LAUNCH_INPUT_DATABASE}}}"
    modules = f"${{input:{LAUNCH_INPUT_MODULES}}}"
    test_module = f"${{input:{LAUNCH_INPUT_TEST_MODULE}}}"
    configurations = []
    for inst in cfg.instances():
        conf = str(cfg.config_file(inst.version))
        label = f"Odoo {inst.version}"
        suffix = f"({inst.name})"
        configurations += [
            _launch_configuration(cfg, inst.version, f"{label} {suffix}", ["-c", conf]),
            _launch_configuration(
                cfg, inst.version, f"{label} shell {suffix}",
                ["shell", "-c", conf, "-d", database],
            ),
            _launch_configuration(
                cfg, inst.version, f"{label} upgrade modules {suffix}",
                ["-c", conf, "-d", database, "-u", modules],
            ),
            _launch_configuration(
                cfg, inst.version, f"{label} test module {suffix}",
                ["-c", conf, "-d", database, "-u", test_module, "--test-enable",
                 "--test-tags", f"/{test_module}", "--stop-after-init"],
            ),
        ]
    launch = {"version": "0.2.0", "configurations": configurations, "inputs": _launch_inputs(cfg)}
    return json.dumps(launch, indent=2) + "\n"


def render_code_workspace(cfg: WorkspaceConfig) -> str:
    workspace = {
        "folders": [{"path": "."}],
        "settings": {"python.terminal.activateEnvironment": True},
    }
    return json.dumps(workspace, indent=2) + "\n"


def _readme_python(choice: InterpreterChoice | None) -> str:
    if choice is None or not choice.python:
        return "host `python3`"
    label = f"{choice.python} (`uv`)" if choice.source == UV_PYTHON else f"{choice.python} (host)"
    # Said in English, like the rest of this file: `InterpreterChoice.describe`
    # is for the UI and is translated, and a generated artifact never is.
    return f"{label} — **outside the supported range**" if choice.out_of_range else label


def _readme_requirement_changes(version: str) -> str:
    substitute = requirement_substitute(version)
    if substitute is None:
        return "—"
    dropped, replacement = substitute
    return f"`{replacement}` instead of `{dropped}`"


def render_workspace_readme(
    cfg: WorkspaceConfig,
    interpreters: dict[str, InterpreterChoice] | None = None,
) -> str:
    """A robust per-workspace README giving any human or AI full context —
    versions, layout, per-version ports/configs, what each venv installs, and
    setup/run commands. ``interpreters`` are the choices the plan built with."""
    version_rows = "\n".join(
        f"| {inst.version} | `{inst.name}` | {cfg.http_port_for(inst.version)} | "
        f"`config/odoo{inst.major}.conf` | `.venv/odoo{inst.major}` |"
        for inst in cfg.instances()
    )
    venv_rows = "\n".join(
        f"| {inst.version} | {_readme_python((interpreters or {}).get(inst.version))} | "
        f"`{setuptools_requirement(inst.version)}` | "
        f"{_readme_requirement_changes(inst.version)} |"
        for inst in cfg.instances()
    )
    oca = ", ".join(cfg.oca_repos) if cfg.oca_repos else "(none)"
    # The language-server file only exists when OdooLS supports a version here.
    has_odools = bool(odools_versions(cfg))
    odools_line = (
        "\n├── odools.toml           # official Odoo language server profiles (Odoo >= 14)"
        if has_odools
        else ""
    )
    editor_hint = (
        " Install the recommended\nofficial Odoo extension (`Odoo.odoo`) and pick this workspace's profile for "
        "your version from the status\nbar (**Change Configuration**)."
        if has_odools
        else ""
    )
    return f"""# {cfg.name} — Odoo development workspace

Generated by **odoo_dwg**. This workspace hosts one Odoo Community instance per configured version, each with
its own virtualenv, config, and port. Odoo/OCA source lives in the shared cache at `{cfg.repos_dir}` and is
reused across workspaces.

## Versions

| Version | Instance | HTTP port | Config | Venv |
|---------|----------|-----------|--------|------|
{version_rows}

- OCA repositories: {oca}
- Custom addons: `addons-custom/` · OCA addons (symlinks): `addons-oca/`

## What each venv installs

| Version | Python | setuptools | Requirement changes |
|---------|--------|------------|---------------------|
{venv_rows}

`scripts/setup_venv.sh` rebuilds each venv the same way. Odoo ≤ 16 needs `setuptools<81` because it imports
`pkg_resources` at startup; Odoo ≤ 13 needs `setuptools<58` because `vatnumber` still uses `use_2to3`. A
requirement change replaces a deprecated project the branch still pins with its declared successor; the shared
clone is not modified. If a venv fails with `No module named 'pkg_resources'`, run
`.venv/odoo<major>/bin/pip install 'setuptools<81'`.

## Layout

```
{cfg.name}/
├── addons-custom/        # your modules
├── addons-oca/           # symlinks into the shared OCA cache
├── config/odoo<major>.conf
├── .venv/odoo<major>/    # one venv per version
├── scripts/              # setup_venv.sh, run-odoo<major>.sh
├── .vscode/              # tasks.json, launch.json, settings.json, extensions.json
├── workspace.json        # this workspace's profile — the manage flow reads it
├── README.md             # this file{odools_line}
└── {cfg.name}.code-workspace
```

## Setup & run

The venvs are already built. Create a database, then launch:

```bash
# From this workspace directory, on the Linux host:
createdb -h {cfg.db_host} -U {cfg.db_user} {cfg.name}    # once; the name F5 offers by default
bash scripts/run-odoo{cfg.instances()[0].major}.sh          # launch the {cfg.versions[0]} instance
```

Then open <http://{cfg.db_host}:{cfg.http_port_for(cfg.versions[0])}/web/login>. You can also create the database
from Odoo's own database manager at `/web/database/manager`; its master password is `admin`, set by
`admin_passwd` in each `config/odoo<major>.conf`. **`-h {cfg.db_host} -U {cfg.db_user}` is not optional**:
the development role is trusted over loopback TCP, not over the Unix socket, so a bare `createdb` fails with
`role "<your user>" does not exist`.

`bash scripts/setup_venv.sh` **re**builds every venv from scratch (the workspace was generated with them
built); run it after changing an interpreter or to repair one.

Mail goes nowhere outside this host: each `odoo.conf` points SMTP at `127.0.0.1:1025`. If the local capture
(Mailpit) is installed, read what Odoo sent at <http://localhost:8025>.

Each instance's `addons_path` is composed of `addons-custom`, the OCA repos, then the shared Odoo `addons`.
Open `{cfg.name}.code-workspace` in VSCode for tasks and debug launch configs.{editor_hint}

## Debugging (F5)

`.vscode/launch.json` has four configurations per version, all under the debugger:

| Configuration | Runs | Asks for |
|---|---|---|
| `Odoo <version>` | the server | — |
| `Odoo <version> shell` | `odoo-bin shell`: a Python REPL with `env` bound to a database | database |
| `Odoo <version> upgrade modules` | the server, upgrading modules on start (`-u`) | database, modules |
| `Odoo <version> test module` | one module's tests (`--test-enable --test-tags /<module>`), then stops | database, module |

The database prompt offers `{cfg.name}`. Breakpoints in your addons stop in all four, including in migration
scripts and tests. Odoo 12 runs tests only on a database created with demo data.

The shared Odoo clones are shallow (no history). For `git log`/`git blame` on the Odoo source, run
`git -C {cfg.repos_dir}/odoo-<version> fetch --unshallow` once.
"""


# --- migration (F3) --------------------------------------------------------


# Overrides applied via ``uv pip install --overrides``: an entry replaces every
# requirement of the same package name during resolution (entries for packages the
# requirements never pull are ignored). Odoo branches 16/17/18 all pin
# gevent==21.8.0 for python_version == '3.10' (the Jammy assumption), but that
# release predates CPython 3.10 (no cp310 wheel) and its sdist no longer compiles
# under modern Cython. The official requirements' own pins for the 3.11 row —
# gevent==22.10.2 + greenlet==2.0.2 — ship cp310 wheels, so we lift to those.
_PY310_OVERRIDES = ("gevent==22.10.2", "greenlet==2.0.2")


#: The last major whose ``requirements.txt`` pins ``pyldap``. 12.0 pins
#: ``pyldap==2.4.28``; 13.0 already pins ``python-ldap==3.1.0``.
PYLDAP_LAST_MAJOR = 12

# `pyldap` was a temporary Python-3 fork of `python-ldap`. Its own PyPI page says
# so: "THIS FORK IS DEPRECATED. The pyldap fork was merged back into python-ldap,
# and released as python-ldap 3.0.0." 2.4.28's setup passes `-R` to the linker — a
# SunOS flag GCC rejects — so it cannot build on a current toolchain:
#     cc: error: unrecognized command-line option '-R'
# The replacement is not a choice this project made: it is the package the fork
# became, at the version Odoo itself moved to in 13.0.
# `--overrides` pins versions; it cannot rename a package. Adding python-ldap
# alone left pyldap==2.4.28 in the resolution and it failed to build exactly as
# before. The fork's own final release is the bridge: 3.0.0.post1 contains no
# code and only requires python-ldap.
_PYLDAP_OVERRIDE = [
    "# pyldap==2.4.28 passes '-R' to cc and cannot build. 3.0.0.post1 is the fork's",
    "# own last release, which only requires python-ldap — the package it became.",
    "pyldap==3.0.0.post1; sys_platform != 'win32'",
    "# and the version Odoo itself moved to in 13.0, rather than whatever is latest.",
    "python-ldap==3.1.0; sys_platform != 'win32'",
]


def render_migration_overrides(version: str, python: str | None = None) -> str:
    """Per-version requirements repair for old branches, fed to ``--overrides``.

    Only the Python-3.10 steps need repairs today (see ``_PY310_OVERRIDES``);
    other interpreters resolve their branch's pins to installable wheels/sdists
    (validated on WSL: Odoo 15 on 3.8, Odoo 18 on 3.12).

    ``python`` is the interpreter the step will actually run, which differs from
    the matrix recommendation when the operator pinned the step; the repair must
    follow the interpreter in use, not the default one."""
    if python is None:
        python, _method = migration_interpreter(version)
    lines = [
        f"# Generated by odoo_dwg — requirements overrides for Odoo {version}"
        f" (Python {python})."
    ]
    if python and python_tuple(python)[:2] == (3, 10):
        lines.append("# gevent==21.8.0 has no cp310 wheel; lift to the branch's own 3.11 pins.")
        lines.extend(_PY310_OVERRIDES)
    if odoo_major(version) <= PYLDAP_LAST_MAJOR:
        lines.extend(_PYLDAP_OVERRIDE)
    return "\n".join(lines) + "\n"


def render_migration_scaffold(module: str, version: str, findings: list) -> str:
    """An additive ``pre-migration.py`` stub for one module/step: openupgradelib
    import plus one commented TODO per candidate finding. Inert until a developer
    reviews it — the header says so. ``findings`` are ``analysis.Finding``."""
    lines = [
        f"# Generated by odoo_dwg staging for {module} -> Odoo {version}.",
        "# REVIEW REQUIRED: these are CANDIDATE findings from the OpenUpgrade",
        "# analysis files — confirm each one, then implement and uncomment.",
        "# This stub does nothing until you complete it.",
        "from openupgradelib import openupgrade",
        "",
    ]
    for finding in findings:
        record = finding.record
        what = "model" if record.kind == "removed_model" else "field"
        # The path comes from the operator's own module tree, which this tool did
        # not write: a file name may legally contain a newline, and this comment
        # is a line of a Python file OpenUpgrade *executes*. `repr` keeps it one
        # line whatever it holds.
        lines.append(
            f"# TODO {record.model}: {what} '{record.name}' removed in {version}"
            f" (seen at {finding.path!r}:{finding.line})"
        )
    lines += [
        "",
        "",
        "@openupgrade.migrate()",
        "def migrate(env, version):",
        "    pass  # TODO: implement the reviewed operations above",
    ]
    return "\n".join(lines) + "\n"


def render_migration_report(
    env: MigrationEnv,
    runs: list,
    logs: dict[str, str],
    decisions: dict[str, list] | None = None,
    open_items: list[tuple[str, str]] | None = None,
) -> str:
    """The report an operator works through after — or during — a chain.

    ``runs`` are `runlog.Run`, oldest first; ``logs`` is the summarised Odoo log
    per step of the latest run; ``decisions`` the firewall's answers inside each
    step's window; ``open_items`` what is still unresolved, which is the section
    the whole thing exists for.

    Nothing here says what a warning *means*. Level, logger and count are what
    the line carries; naming categories would be asserting something about
    OpenUpgrade that this project has not verified.
    """
    lines = [
        f"# Migration report — {env.source} → {env.target}",
        "",
        "Generated by odoo_dwg from the driver's own step log, each step's Odoo log, and the",
        "outbound firewall's journal. **A step that was skipped ran nothing this time**: its",
        "warnings are in the run that first performed it.",
        "",
    ]

    if open_items:
        lines += ["## Still open", ""]
        lines += [f"- **{what}** — {detail}" for what, detail in open_items]
        lines.append("")
    else:
        lines += ["## Still open", "", "Nothing. Every step of the latest run finished, and no step's",
                  "log holds an error.", ""]

    lines += ["## Runs", "", "| Run | Chain | Started | Outcome | Steps |", "| --- | --- | --- | --- | --- |"]
    for run in runs:
        done = sum(1 for step in run.steps if step.outcome in ("ok", "skip"))
        lines.append(
            f"| `{run.run}` | {run.chain or '—'} | {run.started} | {run.outcome} | "
            f"{done}/{len(run.steps)} |"
        )
    lines.append("")

    if not runs:
        lines += ["No run has been recorded yet: the driver writes one line per event as it goes.", ""]
        return "\n".join(lines) + "\n"

    latest = runs[-1]
    lines += [f"## Latest run (`{latest.run}`)", ""]
    for step in latest.steps:
        lines += [f"### Step {step.version} — {step.outcome}" + (f" (exit {step.code})" if step.code else ""), ""]
        lines.append(f"- started `{step.started or '—'}`, ended `{step.ended or '—'}`")
        if step.outcome == "skip":
            lines += ["- already checkpointed, so nothing ran this time", ""]
            continue

        entries = logs.get(step.version) or []
        if entries:
            lines += ["", "| Level | Logger | Count | First message |", "| --- | --- | --- | --- |"]
            lines += [
                f"| {entry.level} | `{entry.logger}` | {entry.count} | {entry.first[:160]} |"
                for entry in entries
            ]
        else:
            lines.append("- its log holds no error or warning")

        answers = (decisions or {}).get(step.version) or []
        if answers:
            lines += ["", "**The step reached outside its own machine:**", ""]
            lines += [
                f"- `{answer.action}` {answer.host} ×{answer.count} (rule `{answer.rule}`)"
                for answer in answers
            ]
        lines.append("")

    return "\n".join(lines) + "\n"


def render_staging_report(
    module: str,
    steps: list[tuple[str, str, list, str | None]],
    promoted: list[tuple[str, str]] | None = None,
) -> str:
    """The per-module staging report the developer works through. ``steps`` is
    ``(version, tool_log_text, findings, scaffold_path_or_None)`` per step; the
    tool's log is carried verbatim. States the boundary: staging is a prepared
    starting point, never a finished migration."""
    lines = [
        f"# Staging report — {module}",
        "",
        "Generated by odoo_dwg. **Staging is a prepared starting point: your review",
        "completes the migration.** Findings are candidates (name matches with the",
        "owning model present), not proof.",
        "",
        "Each stage directory is a throwaway git repository: `odoo-module-migrate`",
        "refuses to run outside one, so staging creates it and commits the",
        "pre-migration state into it. It is not yours and is not pushed anywhere.",
        "",
    ]
    for version, log_text, findings, scaffold in steps:
        # The tool's log is carried verbatim, so the fence has to be longer than
        # any run of backticks in it — otherwise the log ends the block early and
        # the rest of the report is read as markdown.
        body = log_text.rstrip() or "(no output captured)"
        fence = "```"
        while fence in body:
            fence += "`"
        lines += [f"## Step {version}", "", "### odoo-module-migrate output (verbatim)", fence]
        lines.append(body)
        lines += [fence, ""]
        if findings:
            lines.append("### Candidate findings (confirm each)")
            for finding in findings:
                record = finding.record
                what = "model" if record.kind == "removed_model" else "field"
                lines.append(
                    f"- `{record.model}` {what} `{record.name}` removed in {version}"
                    f" — seen at `{finding.path!r}:{finding.line}`"
                )
            lines.append("")
        else:
            lines += ["### Candidate findings", "None detected.", ""]
        if scaffold:
            lines += [f"Scaffold written: `{scaffold}` — review and complete it.", ""]
    if promoted:
        lines += [
            "## Promoted copy",
            "",
            "Your reviewed code lives outside this environment; this environment's copy is a working",
            "copy of it. Neither is authoritative — where they differ, you decide which is right.",
            "",
            "| Step | Environment vs promoted |",
            "| --- | --- |",
        ]
        lines += [f"| {version} | {state} |" for version, state in promoted]
        lines.append("")
    return "\n".join(lines) + "\n"


def render_migration_conf(env: MigrationEnv, version: str) -> str:
    """Per-step ``odoo.conf`` for a migration step (no HTTP — runs stop-after-init).

    With an intake, every step uses the environment's ``data_dir``, as the source
    and ``open_for_testing.sh`` do: a step that looked in Odoo's default found no
    attachment of the client's, and the migrated database could not be opened
    with them either."""
    data_dir = [f"data_dir = {env.data_dir}"] if env.intake is not None else []
    lines = [
        "[options]",
        f"; Generated by odoo_dwg — OpenUpgrade step to Odoo {version}.",
        f"addons_path = {env.addons_path(version)}",
        *data_dir,
        "",
        f"db_host = {env.db_host}",
        f"db_port = {env.db_port}",
        f"db_user = {env.db_user}",
        "",
        "workers = 0",
        "max_cron_threads = 0",
        "",
        *_smtp_to_capture(),
    ]
    return "\n".join(lines) + "\n"


def _render_step_hook(env: MigrationEnv) -> str:
    """``step_hook``: the operator's SQL around one step, when there is some.

    A client's data can break a migration script no source anticipates: the first
    client's 14.0 step stopped because OpenUpgrade gives every bank statement line
    a journal entry, and some lines belonged to closed banks whose account is
    deprecated. What to do about it is a decision about that client's data, so it
    lives in the environment (``hooks/<version>-pre.sql``, ``-post.sql``), runs in
    one transaction, and is named in the log and the step record. A step with no
    file runs as before."""
    hooks = shlex.quote(str(env.hooks_dir))
    return (
        "# The operator's SQL around a step, from hooks/<version>-pre.sql and -post.sql.\n"
        "step_hook() {\n"
        f'  local file={hooks}/"$1-$2.sql"\n'
        '  [ -f "$file" ] || return 0\n'
        '  psql -X -q -1 -v ON_ERROR_STOP=1 -d "$DB" -f "$file" >/dev/null \\\n'
        '    || die "$1: the $2-step hook $file failed"\n'
        '  echo "[hook] $1 $2: $file"\n'
        '  mark "$1" "hook-$2" "$file"\n'
        "}\n"
    )


def _render_driver_filestore(env: MigrationEnv) -> str:
    """``give_filestore``: the working database's attachments, before any step.

    Odoo looks in ``<data_dir>/filestore/<database>``. With an intake the client's
    files are the reference's, so the working database gets hard links to them —
    no space, and Odoo never rewrites an attachment file in place. Without an
    intake there is nothing to give, and the function says so by doing nothing."""
    if env.intake is None:
        return "give_filestore() { :; }\n"
    q = shlex.quote
    store = env.data_dir / "filestore"
    reference = store / env.intake.reference_database
    return (
        "# The client's attachments, as hard links to the reference's: the steps read\n"
        "# them from the environment's data_dir, which every step's conf names.\n"
        "give_filestore() {\n"
        f'  if [ -d {q(str(reference))} ] && [ ! -e {q(str(store))}/"$DB" ]; then\n'
        f"    mkdir -p {q(str(store))}\n"
        f'    cp -al {q(str(reference))} {q(str(store))}/"$DB" \\\n'
        '      || die "could not give \'$DB\' a filestore"\n'
        f'    echo "[filestore] $DB: hard links to {env.intake.reference_database}\'s attachments"\n'
        "  fi\n"
        "}\n"
    )


def _render_step_preconditions(env: MigrationEnv, version: str) -> str:
    """The step's own code must be on disk before it claims to migrate anything.

    Odoo neither fails nor says anything when ``--upgrade-path`` points at a
    directory that is not there: it simply finds no scripts, and the step would
    be checkpointed as migrated. A clone interrupted mid-way is enough, since
    generation skips a checkout directory that merely exists."""
    if env.uses_legacy_layout(version):
        # The fork *is* Odoo here, so a missing checkout already fails loudly on
        # its own addons_path; its scripts live inside each add-on.
        needed = [(env.openupgrade_clone_dir(version) / "addons", "the OpenUpgrade fork's add-ons")]
    else:
        needed = [
            (env.upgrade_scripts_dir(version), "the OpenUpgrade scripts"),
            (env.openupgrade_clone_dir(version) / "openupgrade_framework", "openupgrade_framework"),
        ]
    lines = [
        f'  [ -d {shlex.quote(str(path))} ] || '
        f'die "{version}: {what} not found at {path} — regenerate the environment"\n'
        for path, what in needed
    ]
    # Coverage again, against the database as it is *now*. The preflight reads
    # the source database once, so a module the chain auto-installs along the way
    # is invisible to it: `partner_firstname_portal` appeared in an OCA
    # repository at 18.0, was auto-installed there, and vanished from the
    # repository at 19.0 — installed, with no code, and nothing had asked.
    sources = " ".join(shlex.quote(str(path)) for path in env.coverage_dirs(version))
    query = (
        # An author spread over lines in its manifest split its row in two, and
        # the second line was checked as a module (16.0 web_search_with_and).
        "SELECT name || E'\\t' || regexp_replace(coalesce(author, ''), '[\\n\\r\\t]+', ' ', 'g') "
        "FROM ir_module_module "
        "WHERE state='installed' ORDER BY name"
    )
    lines.append(
        f'  step_modules=$(psql -X -d "$DB" -tAc {shlex.quote(query)}) '
        f'|| die "{version}: could not list the installed modules"\n'
    )
    lines.append(
        # By the module *name*, which is the first field: the step's rows are
        # "name<TAB>author" and the known list holds names, so comparing whole
        # lines matched nothing and made every module look new.
        '  new_modules=$(printf \'%s\\n\' "$step_modules" | '
        'awk -F\'\\t\' \'NR==FNR {known[$0]; next} $1 != "" && !($1 in known)\' '
        '"$LOGS/known-modules.txt" -)\n'
    )
    lines.append(
        f'  [ -z "$new_modules" ] || ODWG_MODULES_TSV="$new_modules" coverage_step {version} '
        f"{shlex.quote(str(env.apriori_file(version)))} "
        f"{shlex.quote(str(env.addons_custom_dir(version)))} "
        f"{shlex.quote(str(env.decisions_file))} {sources} >/dev/null "
        f'|| die "{version}: a module installed since the preflight resolves nowhere '
        f'(see [coverage] lines above)"\n'
    )
    lines.append(
        f'  ODWG_MODULES_TSV="$step_modules" python_deps_step {version} '
        f"{shlex.quote(str(env.venv_dir(version) / 'bin' / 'python'))} "
        f"{shlex.quote(str(env.apriori_file(version)))} "
        f"{shlex.quote(str(odoo_module_file(env, version)))} {sources} "
        f'|| die "{version}: its modules need Python libraries its venv lacks (see [python] '
        f'lines above) — regenerating the environment offers to install them"\n'
    )
    return "".join(lines)


def _native_step_command(env: MigrationEnv, version: str) -> str:
    """The command that upgrades the working database to one version.

    Two shapes, because OpenUpgrade changed layout at 14. From 14 the scripts sit
    under ``--upgrade-path`` and ``openupgrade_framework`` is loaded. Up to 13 they
    live inside each add-on and neither flag exists — that step runs the fork's own
    ``odoo-bin`` and depends entirely on the add-ons path reaching the fork's
    ``addons``. The path comes from the step's config file, which states it
    explicitly: an inherited or defaulted path that resolves to some other copy of
    Odoo's add-ons skips every add-on migration while the step still succeeds."""
    venv = env.venv_dir(version)
    conf = env.config_file(version)
    log = env.logs_dir / f"{version}.log"
    odoo_bin = env.odoo_bin(version)
    q = shlex.quote
    run = f'{q(f"{venv}/bin/python")} {q(str(odoo_bin))} -c {q(str(conf))} -d "$DB"'
    if env.uses_legacy_layout(version):
        return f"{run} --update all --stop-after-init --logfile={q(str(log))}"
    scripts = env.upgrade_scripts_dir(version)
    return (
        f"{run} --upgrade-path={q(str(scripts))} --update all --stop-after-init "
        f"--load=base,web,openupgrade_framework --logfile={q(str(log))}"
    )


#: The step after which OpenUpgrade has left statement lines' ``is_reconciled`` stale.
STATEMENT_LINES_REPAIR_STEP = "14.0"

#: The only lines the defect can leave wrong: stored as reconciled while their move still
#: has a line on the journal's suspense account. The repair and ``migrate audit`` both
#: select them with this, so they agree on what is affected.
STALE_RECONCILED_LINES_FROM = """FROM account_bank_statement_line l
    JOIN account_move m ON m.id = l.move_id
    JOIN account_journal j ON j.id = m.journal_id
    WHERE l.is_reconciled AND EXISTS (
        SELECT 1 FROM account_move_line aml
        WHERE aml.move_id = m.id AND aml.account_id = j.suspense_account_id)"""

#: Run by the 14.0 Odoo's shell: Odoo's own rule, on those lines. Selected in SQL, so a
#: database with many reconciled lines does not load them all.
_STATEMENT_LINES_REPAIR = f"""\
env.cr.execute(\"\"\"
    SELECT l.id {STALE_RECONCILED_LINES_FROM}
\"\"\")
lines = env["account.bank.statement.line"].browse([row[0] for row in env.cr.fetchall()])
lines._compute_is_reconciled()
lines.flush()
env.cr.commit()
print("[repair] statement lines stored as reconciled with a suspense line: %d, still "
      "reconciled after the recompute: %d" % (len(lines), len(lines.filtered("is_reconciled"))))
"""

#: Run by the same shell: the SII certificate file the OCA 14.0 migration of
#: ``l10n_es_aeat_sii_oca`` leaves behind. It creates each certificate from the old
#: ``l10n_es_aeat_sii`` record but moves attachments only, and in 12.0 the file is a
#: column (base64, the form the ORM takes). Guarded: nothing without both tables and
#: OpenUpgrade's legacy link.
_SII_CERTIFICATE_REPAIR = """\
env.cr.execute(\"\"\"
    SELECT count(*) = 3 FROM information_schema.columns
    WHERE (table_name, column_name) IN (('l10n_es_aeat_sii', 'file'),
        ('l10n_es_aeat_certificate', 'openupgrade_legacy_14_0_l10n_es_aeat_sii_id'),
        ('l10n_es_aeat_certificate', 'id'))
\"\"\")
carried = 0
if env.cr.fetchone()[0] and "l10n.es.aeat.certificate" in env:
    env.cr.execute(\"\"\"
        SELECT c.id, s.file FROM l10n_es_aeat_certificate c
        JOIN l10n_es_aeat_sii s ON s.id = c.openupgrade_legacy_14_0_l10n_es_aeat_sii_id
        WHERE s.file IS NOT NULL
    \"\"\")
    for certificate_id, data in env.cr.fetchall():
        certificate = env["l10n.es.aeat.certificate"].browse(certificate_id)
        if not certificate.file:
            certificate.file = bytes(data)
            carried += 1
    env.cr.commit()
print("[repair] SII certificate files carried to the new model: %d%s" % (carried,
      "; obtain the keys again on the new server, with the certificate's password" if carried else ""))
"""


def _render_step_repair(env: MigrationEnv, version: str) -> str:
    """What a step's known OpenUpgrade defect needs, after its post hook.

    OpenUpgrade's 14.0 account post-migration gives every statement line without an
    entry one through the ORM, then computes the lines' ``is_reconciled`` in raw SQL
    with no flush in between, so the ORM's stale values (computed before the suspense
    line existed) are written over it. Lines still in the suspense account end up
    stored as reconciled and the reconciliation screen hides them. Odoo's own
    ``_compute_is_reconciled``, identical in 14.0 and 18.0, recomputes them: only the
    lines stored as reconciled that still have a suspense line. The same run carries the
    SII certificate file the OCA 14.0 migration leaves in the old table. Only for a
    source up to 13.0: from 14.0 every line already has its entry, and the certificate
    model already exists."""
    if version != STATEMENT_LINES_REPAIR_STEP or \
            odoo_major(env.source) > LEGACY_LAYOUT_MAX_MAJOR:
        return ""
    q = shlex.quote
    python = q(f"{env.venv_dir(version)}/bin/python")
    shell = (f'{python} {q(str(env.odoo_bin(version)))} shell -c {q(str(env.config_file(version)))} '
             f'-d "$DB" --no-http --logfile={q(str(env.logs_dir / f"{version}.log"))}')
    return (
        "  # OpenUpgrade 14.0 stores unreconciled statement lines as reconciled (an ORM\n"
        "  # flush over its own SQL); Odoo's own method recomputes them. The OCA 14.0\n"
        "  # SII migration leaves the certificate file behind; it is carried here.\n"
        f"  {shell} <<'ODWG_REPAIR' || die \"{version}: the repairs after the step failed "
        "(statement lines' reconciled flag, SII certificate file)\"\n"
        f"{_STATEMENT_LINES_REPAIR}{_SII_CERTIFICATE_REPAIR}ODWG_REPAIR\n"
        f'  mark "{version}" repair statement-lines-is-reconciled\n'
        f'  mark "{version}" repair sii-certificate-file\n'
    )


#: The client-modules stage's checkpoint and step-record name, after the target step.
def modules_stage(env: MigrationEnv) -> str:
    return f"{env.target}-modules"


def carry_source() -> str:
    """``odoo_dwg/carry.py`` as the driver embeds it: the file itself, so the driver and
    ``migrate modules`` compute the same plan."""
    return resources.files("odoo_dwg").joinpath("carry.py").read_text(encoding="utf-8")


#: Run by the target's Odoo shell: the renames the plan lists, with OpenUpgrade's own
#: library (in every chain venv, since OpenUpgrade requires it). ``merge_modules`` folds a
#: module into one that already exists, so several old modules can share one new name.
_MODULES_RENAME = """\
import json, os
from openupgradelib import openupgrade
with open(os.environ["ODWG_MODULES_PLAN"], encoding="utf-8") as handle:
    plan = json.load(handle)
pairs = [tuple(pair) for pair in plan["renames"]]
if pairs:
    openupgrade.update_module_names(env.cr, pairs, merge_modules=True)
    env.cr.commit()
for old, new in pairs:
    print("[modules] %s -> %s" % (old, new))
"""

#: Run by the same shell once everything is installed: the plan's uninstalls. Odoo also
#: uninstalls whatever depends on them, so a module no decision drops stops it first.
_MODULES_UNINSTALL = """\
import json, os
with open(os.environ["ODWG_MODULES_PLAN"], encoding="utf-8") as handle:
    plan = json.load(handle)
Module = env["ir.module.module"]
wanted = set(plan["updates"]) | set(plan["installs"])
done = set(Module.search([("name", "in", list(wanted)), ("state", "=", "installed")]).mapped("name"))
if wanted - done:
    # Odoo skips a module it cannot load and still exits 0: never uninstall the old
    # modules when what replaces them is not there.
    print("[modules] not installed after the update: %s; nothing uninstalled"
          % ", ".join(sorted(wanted - done)))
    raise SystemExit(1)
modules = Module.search(
    [("name", "in", plan["uninstalls"]), ("state", "in", ("installed", "to upgrade"))])
along = modules.downstream_dependencies() - modules
if along:
    print("[modules] uninstalling %s would also remove %s, which no decision drops or replaces"
          % (", ".join(sorted(modules.mapped("name"))), ", ".join(sorted(along.mapped("name")))))
    raise SystemExit(1)
if modules:
    modules.button_immediate_uninstall()
print("[modules] uninstalled: %s" % (", ".join(sorted(modules.mapped("name"))) or "none"))
"""


def _render_modules_stage(env: MigrationEnv) -> str:
    """The client's modules at the target: renamed, replaced or dropped as decided.

    After the target step the client's old modules are still installed with no code, their
    tables and identifiers intact; that is what a rename needs. The decisions are read when
    the stage runs, through ``carry.py`` embedded verbatim, so editing them needs no
    regeneration. Plain Odoo runs here, without OpenUpgrade's framework: the client's modules
    migrate with their own scripts. The order is the point: renames, then one run that
    updates and installs, then the uninstalls, since an old module can be the only owner of a
    table its replacement adopts."""
    q = shlex.quote
    target = env.target
    stage = modules_stage(env)
    binary = f"{q(f'{env.venv_dir(target)}/bin/python')} {q(str(env.odoo_bin(target)))}"
    args = (f'-c {q(str(env.config_file(target)))} -d "$DB" '
            f'--logfile={q(str(env.logs_dir / f"{stage}.log"))}')
    odoo = f"{binary} {args}"
    shell = f"{binary} shell {args} --no-http"
    sources = " ".join(q(str(p)) for p in env.coverage_dirs(target))
    return f"""
# --- stage: the client's modules at {target} (renamed, replaced, dropped) ---
# carry.py, embedded verbatim: the plan `odoo-dwg migrate modules` prints. It is computed
# once, against the database, so a module the database does not have is only skipped.
carry() {{
  python3 - {q(str(env.decisions_file))} {q(env.source)} {q(target)} "$MODULES_PLAN" {sources} <<'ODWG_CARRY'
{carry_source()}ODWG_CARRY
}}
modules_fail() {{ mark "{stage}" fail "$1"; die "{stage}: $2"; }}
if have_ck "{stage}"; then
  echo "[skip] {stage} already carried"
  mark "{stage}" skip
else
  if [ "$AT_TARGET" != 1 ] && [ -f "$MODULES_DIRTY" ]; then
    # An earlier carry changed the working database and left no checkpoint (it failed,
    # or --redo-modules removed it): only the target checkpoint can be trusted.
    mark - restore "{target}"
    restore_ck "{target}"
    rm -f "$MODULES_DIRTY"
  fi
  installed=$(psql -X -At -d "$DB" -c \\
    "SELECT name FROM ir_module_module WHERE state IN ('installed', 'to upgrade')") \\
    || die "{stage}: could not list the installed modules"
  code=0
  ODWG_INSTALLED="$installed" carry > "$LOGS/{stage}.lists" || code=$?
  if [ "$code" -eq 3 ]; then
    echo "[modules] nothing to carry"
    mark "{stage}" skip "nothing to carry"
  elif [ "$code" -ne 0 ]; then
    modules_fail "$code" "stopped before changing the database (see [modules] lines above)"
  else
    {{ read -r UPDATES; read -r INSTALLS; }} < "$LOGS/{stage}.lists"
    echo "[step] carrying the client's modules at {target}"
    mark "{stage}" start
    # From here the working database is no longer the target checkpoint until this
    # stage writes its own; a run that stops before that restores the target first.
    : > "$MODULES_DIRTY"
    ( step_hook "{stage}" pre ) || modules_fail hook "the pre hook failed"
    ODWG_MODULES_PLAN="$MODULES_PLAN" {shell} <<'ODWG_RENAME' \\
      || modules_fail rename "the renames failed — see the output above and {env.logs_dir}/{stage}.log"
{_MODULES_RENAME}ODWG_RENAME
    mark "{stage}" renamed "$(python3 -c 'import json, sys; print(" ".join("%s>%s" % tuple(p) for p in json.load(open(sys.argv[1]))["renames"]))' "$MODULES_PLAN")"
    if [ -n "$UPDATES$INSTALLS" ]; then
      code=0
      {odoo} ${{UPDATES:+-u "$UPDATES"}} ${{INSTALLS:+-i "$INSTALLS"}} --stop-after-init || code=$?
      [ "$code" -eq 0 ] \\
        || modules_fail "$code" "updating and installing failed — see {env.logs_dir}/{stage}.log"
      mark "{stage}" updated "$UPDATES"
      mark "{stage}" installed "$INSTALLS"
    fi
    ODWG_MODULES_PLAN="$MODULES_PLAN" {shell} <<'ODWG_UNINSTALL' \\
      || modules_fail uninstall "the uninstalls failed or were refused — see [modules] lines above"
{_MODULES_UNINSTALL}ODWG_UNINSTALL
    mark "{stage}" uninstalled "$(python3 -c 'import json, sys; print(" ".join(json.load(open(sys.argv[1]))["uninstalls"]))' "$MODULES_PLAN")"
    ( step_hook "{stage}" post ) || modules_fail hook "the post hook failed"
    neutralise "{stage}"
    checkpoint "{stage}"
    rm -f "$MODULES_DIRTY"
    mark "{stage}" ok
  fi
fi"""


def render_migration_constraints(version: str) -> str | None:
    """Build constraints for a step whose dependencies a current toolchain cannot
    build as pinned, or ``None`` when the step needs none.

    Distinct from the requirements overrides: those change *what* is installed,
    these constrain the environment packages are *built* with. The 13.0 branch
    needs it because ``vatnumber==1.2`` still calls ``use_2to3``, which setuptools
    removed in 58."""
    if odoo_major(version) > LEGACY_LAYOUT_MAX_MAJOR:
        return None
    return (
        f"# Generated by odoo_dwg — build constraints for Odoo {version}.\n"
        "# vatnumber==1.2 uses use_2to3, removed in setuptools 58.\n"
        "setuptools<58\n"
    )


def _render_preflight_host(env: MigrationEnv) -> str:
    """Bash host-scope preflight: chain tools, PostgreSQL, dump integrity. The
    bash mirror of ``preflight.gather_host_facts`` (see design: the driver must
    stay plain bash, so the checks are rendered, kept in this one function)."""
    lines = [
        "preflight_host() {",
        '  command -v uv >/dev/null 2>&1 || fail "uv not found (needed for the native venvs)"',
    ]
    lines += [
        # -X, like every other psql this project runs: `~/.psqlrc` can hold a
        # `\\c otherdb` or a `\\! command`, none of which is visible in the plan.
        '  psql -X -tAc "SELECT 1" postgres >/dev/null 2>&1 || fail "PostgreSQL not reachable as $PGUSER@$PGHOST:$PGPORT"',
        '  [ -r "$SRC_DUMP" ] || fail "source dump not readable: $SRC_DUMP"',
        '  pg_restore --list "$SRC_DUMP" >/dev/null 2>&1 || fail "pg_restore cannot list $SRC_DUMP — a custom-format dump (pg_dump -Fc) is required"',
        '  echo "[preflight] host checks passed"',
        "}",
    ]
    return "\n".join(lines)


def odoo_module_file(env: MigrationEnv, version: str) -> Path:
    """The step's own ``odoo/modules/module.py``: how it reads external dependencies."""
    return Path(env.odoo_bin(version)).parent / "odoo" / "modules" / "module.py"


def _render_python_deps_helper() -> str:
    """``python_deps_step``: what the step's modules declare, checked in its own venv.

    Run by the step's interpreter, as Odoo checks it: the distribution and its
    version, then the import name. Odoo only checks when it upgrades a module,
    minutes into the step; the first client's chain stopped at 13.0 on
    ``unidecode`` that way. Checked before the step, it fails in seconds and names
    the module and the library."""
    return "\n".join([
        "python_deps_step() {",
        '  local version="$1" py="$2" apriori="$3" odoo_module="$4"; shift 4',
        "  \"$py\" - \"$version\" \"$apriori\" \"$odoo_module\" \"$@\" <<'PYDEPS'",
        "import ast, importlib, os, re, sys, warnings",
        "warnings.simplefilter('ignore')  # pkg_resources' deprecation, on every lookup",
        "version, apriori, odoo_module, *sources = sys.argv[1:]",
        "# Odoo 18 parses a dependency with a version or a marker with `packaging`, and",
        "# fails on it when `packaging` is missing: read from the step's own Odoo.",
        "try:",
        "    strict = 'Package `packaging` is required' in open(odoo_module, encoding='utf-8').read()",
        "except OSError:",
        "    strict = False",
        "renames = {}",
        "try:",
        "    tree = ast.parse(open(apriori, encoding='utf-8').read())",
        "except (OSError, ValueError, SyntaxError):",
        "    tree = None",
        "for node in (tree.body if tree is not None else []):",
        "    if isinstance(node, ast.Assign) and {t.id for t in node.targets",
        "            if isinstance(t, ast.Name)} & {'renamed_modules', 'merged_modules'}:",
        "        try:",
        "            value = ast.literal_eval(node.value)",
        "        except (ValueError, TypeError):",
        "            continue",
        "        if isinstance(value, dict):",
        "            renames.update({str(k): str(v) for k, v in value.items()})",
        "def where(name):",
        "    for src in sources:",
        "        if os.path.isdir(os.path.join(src, name)):",
        "            return os.path.join(src, name)",
        "    return None",
        "def declared(path):",
        "    for manifest in ('__manifest__.py', '__openerp__.py'):",
        "        try:",
        "            data = ast.literal_eval(open(os.path.join(path, manifest), encoding='utf-8').read())",
        "        except (OSError, ValueError, SyntaxError, TypeError):",
        "            continue",
        "        external = data.get('external_dependencies') if isinstance(data, dict) else None",
        "        deps = external.get('python') if isinstance(external, dict) else None",
        "        return [d for d in deps if isinstance(d, str)] if isinstance(deps, list) else []",
        "    return []",
        "def packaging(part):",
        "    for base in ('packaging', 'pkg_resources.extern.packaging',",
        "                 'setuptools._vendor.packaging', 'pip._vendor.packaging'):",
        "        try:",
        "            return importlib.import_module(base + '.' + part)",
        "        except Exception:",
        "            continue",
        "    return None",
        "def problem(dep):",
        r"    if strict and not re.fullmatch(r'[\w\-]+', dep):",
        "        try:",
        "            importlib.import_module('packaging.requirements')",
        "        except Exception:",
        "            return 'packaging is not installed, and this Odoo needs it to read it'",
        "    text, _, marker = dep.partition(';')",
        "    markers = packaging('markers')",
        "    if marker.strip() and markers is not None:",
        "        try:",
        "            if not markers.Marker(marker).evaluate():",
        "                return None",
        "        except Exception:",
        "            pass",
        r"    match = re.match(r'\s*([A-Za-z0-9][A-Za-z0-9._-]*)\s*(.*)$', text)",
        "    if not match:",
        "        return None",
        "    name, spec = match.group(1), match.group(2).strip()",
        "    try:",
        "        from importlib import metadata",
        "        installed = metadata.version(name)",
        "    except Exception:",
        "        try:",
        "            importlib.import_module(name)",
        "            return None",
        "        except Exception:",
        "            return 'not installed'",
        "    specifiers = packaging('specifiers')",
        "    if not spec or specifiers is None:",
        "        return None",
        "    try:",
        "        fits = specifiers.SpecifierSet(spec).contains(installed, prereleases=True)",
        "    except Exception:",
        "        return None",
        "    return None if fits else installed + ' installed'",
        "missing = []",
        "for line in os.environ.get('ODWG_MODULES_TSV', '').splitlines():",
        "    name = line.split('\\t')[0].strip()",
        "    if not name:",
        "        continue",
        "    found = where(name) or (where(renames[name]) if renames.get(name) else None)",
        "    for dep in declared(found) if found else []:",
        "        why = problem(dep)",
        "        if why:",
        "            missing.append((os.path.basename(found), dep, why))",
        "for module, dep, why in missing:",
        "    print('[python] %s needs %s for %s: %s' % (module, dep, version, why), file=sys.stderr)",
        "sys.exit(1 if missing else 0)",
        "PYDEPS",
        "}",
    ])


def _render_coverage_helper() -> str:
    """The bash+python helper the driver uses to judge one step's coverage.

    It applies the same rule as ``preflight.gather_coverage``: resolve what
    OpenUpgrade declares renamed or merged before calling anything missing, then
    split what is left by author — Odoo's own dropped code is a warning the
    upgrade handles, anybody else's is the operator's to supply. It reads
    ``apriori.py`` with ``ast`` at run time (never executing it), which is why
    nothing here needs the checkout at render time.

    Exits non-zero only when the blocking class is non-empty.
    """
    return "\n".join(
        [
            "coverage_step() {",
            '  local version="$1" apriori="$2" customdir="$3" decisions="$4"; shift 4',
            # The module list travels in the environment, never on stdin: the
            # heredoc below *is* python's stdin, so anything piped in is lost and
            # the check would silently pass with nothing to check.
            "  python3 - \"$version\" \"$apriori\" \"$customdir\" \"$decisions\" \"$@\" <<'PYCOV'",
            "import ast, json, os, sys",
            "version, apriori, customdir, decisions_file, *sources = sys.argv[1:]",
            "# What the operator decided about modules no step can resolve. Read",
            "# here and not only by the preflight menu action: without it a",
            "# recorded decision was accepted there and refused by this, which",
            "# left the record inert exactly where it mattered.",
            "decided = {}",
            "try:",
            "    with open(decisions_file, encoding=\"utf-8\") as handle:",
            "        data = json.load(handle)",
            "    # The shape `decisions_to_json` writes: a wrapper object, or a bare",
            "    # list for a file written by hand. Reading only one of them made",
            "    # this see nothing in the file the tool itself produces.",
            "    entries = data.get(\"decisions\") if isinstance(data, dict) else data",
            "    for entry in entries if isinstance(entries, list) else []:",
            "        if isinstance(entry, dict) and entry.get(\"module\"):",
            "            decided[entry[\"module\"]] = entry",
            "except (OSError, ValueError, TypeError):",
            "    pass",
            '# Exact spellings only: OCA authors contain "Odoo" and must not pass.',
            'ODOO_AUTHORS = {"odoo s.a.", "odoo sa", "openerp s.a.", "openerp sa", "odoo"}',
            "renames = {}",
            "try:",
            '    tree = ast.parse(open(apriori, encoding="utf-8").read())',
            "except (OSError, ValueError, SyntaxError):",
            '    print("[coverage] %s: no readable apriori.py — renames unknown" % version,',
            "          file=sys.stderr)",
            "    tree = None",
            "if tree is not None:",
            "    for node in tree.body:",
            "        if not isinstance(node, ast.Assign):",
            "            continue",
            "        names = {t.id for t in node.targets if isinstance(t, ast.Name)}",
            '        if not names & {"renamed_modules", "merged_modules"}:',
            "            continue",
            "        try:",
            "            value = ast.literal_eval(node.value)",
            "        except (ValueError, TypeError):",
            "            continue",
            "        if isinstance(value, dict):",
            "            renames.update({str(k): str(v) for k, v in value.items()",
            "                            if isinstance(v, str)})",
            "def resolves(name):",
            "    return any(os.path.isdir(os.path.join(src, name)) for src in sources)",
            "",
            "def where(name):",
            "    for src in sources:",
            "        if os.path.isdir(os.path.join(src, name)):",
            "            return os.path.join(src, name)",
            "    return None",
            "",
            "def depends_of(path):",
            "    # One key of a manifest, parsed and never executed. A module that",
            "    # resolves but names a dependency that does not is refused by Odoo",
            "    # at load time — after the chain has already run this far.",
            "    for manifest in (\"__manifest__.py\", \"__openerp__.py\"):",
            "        try:",
            "            with open(os.path.join(path, manifest), encoding=\"utf-8\") as handle:",
            "                data = ast.literal_eval(handle.read())",
            "        except (OSError, ValueError, SyntaxError, TypeError):",
            "            continue",
            "        if isinstance(data, dict) and isinstance(data.get(\"depends\"), list):",
            "            return [d for d in data[\"depends\"] if isinstance(d, str)]",
            "        return []",
            "    return []",
            "",
            "# Nothing to resolve against: report that, rather than calling every",
            "# module missing — including `base`, which cannot be dropped.",
            "if not any(os.path.isdir(src) for src in sources):",
            "    print('[coverage] %s: its sources are not on disk — regenerate the"
            " environment' % version, file=sys.stderr)",
            "    raise SystemExit(1)",
            "blocking, dropped, settled, unmet = [], [], [], []",
            'modules_tsv = os.environ.get("ODWG_MODULES_TSV", "")',
            "if not modules_tsv.strip():",
            '    print("[coverage] %s: no module list to check" % version, file=sys.stderr)',
            "    sys.exit(1)",
            "# The list as the *next* step will see it: a module this step renames",
            "# or absorbs answers to its new name from here on, and the next step's",
            "# apriori.py says nothing about the old one. Checking the original at",
            "# every step reported a module absorbed at 13.0 as missing at 14.0 and",
            "# stopped the run, asking for code that should not exist.",
            "carried = []",
            "for line in modules_tsv.splitlines():",
            '    parts = line.strip().split("\\t")',
            "    name = parts[0] if parts else \"\"",
            '    author = parts[1] if len(parts) > 1 else ""',
            "    # The name the operator's database had, kept beside the current one:",
            "    # a decision is recorded against a module, and a rename does not make",
            "    # it a different module.",
            '    original = parts[2] if len(parts) > 2 else name',
            "    if not name:",
            "        continue",
            "    successor = renames.get(name)",
            '    carried.append("%s\\t%s\\t%s" % (successor or name, author, original))',
            "    found = where(name)",
            "    if found is not None:",
            "        absent = [d for d in depends_of(found) if not resolves(d)]",
            "        if absent:",
            "            unmet.append((name, sorted(absent)))",
            "        continue",
            "    if successor and resolves(successor):",
            "        continue",
            "    # Under any name the module has in this chain: the one the",
            "    # operator started with, the one this step knows it by, or the one",
            "    # it is about to become. They copy whichever they were shown.",
            "    answer = next((decided[a] for a in (name, original, successor)",
            "                   if a and a in decided), None)",
            "    if answer:",
            "        # Applied only because the module resolves nowhere and has no",
            "        # successor that does — the sources are never overruled.",
            "        settled.append((name, answer.get(\"decision\", \"\"), answer.get(\"reason\", \"\")))",
            "    elif author.strip().lower() in ODOO_AUTHORS:",
            "        dropped.append(name)",
            "    else:",
            "        blocking.append(name)",
            "for name in dropped:",
            '    print("[coverage] %s is not in %s and is not renamed — Odoo dropped it; '
            'OpenUpgrade removes it" % (name, version), file=sys.stderr)',
            "for name, decision, reason in settled:",
            '    print("[coverage] %s: %s for %s — as you recorded%s" % (name, decision, version,',
            '          (" (" + reason + ")") if reason else ""), file=sys.stderr)',
            "for name, absent in unmet:",
            '    print("[coverage] %s needs %s for %s, which resolves nowhere"',
            '          % (name, ", ".join(absent), version), file=sys.stderr)',
            "for name in blocking:",
            '    print("[coverage] %s missing for %s — place it in %s" % (name, version, customdir),',
            "          file=sys.stderr)",
            "# stdout carries the list forward; every diagnostic goes to stderr.",
            'print("\\n".join(carried))',
            "sys.exit(1 if blocking or unmet else 0)",
            "PYCOV",
            "}",
        ]
    )


def _render_preflight_db(env: MigrationEnv) -> str:
    """Bash database-scope preflight, run right after the fresh 00_source restore
    (a resumed database is mid-chain, so the version check only holds there):
    declared-source match from ir_module_module, then per-step addons coverage.

    Coverage asks for each module's author as well as its name, because that is
    what separates a core module Odoo dropped (the upgrade removes it) from code
    the step genuinely needs."""
    source_major = odoo_major(env.source)
    lines = [
        _render_coverage_helper(),
        "",
        _render_python_deps_helper(),
        "",
        "preflight_db() {",
        "  local base_ver blocking=0 next_tsv",
        '  base_ver=$(psql -X -d "$DB" -tAc "SELECT latest_version FROM ir_module_module WHERE name=\'base\'") '
        '|| fail "could not query the restored database \'$DB\'"',
        f'  case "$base_ver" in {source_major}.*) ;; *) fail "database base version \'$base_ver\' does not match declared source {env.source}";; esac',
        '  modules_tsv=$(psql -X -d "$DB" -tAc "SELECT name || E\'\\t\' || regexp_replace(coalesce(author, \'\'), \'[\\n\\r\\t]+\', \' \', \'g\') FROM ir_module_module WHERE state=\'installed\' ORDER BY name") '
        '|| fail "could not list the installed modules of \'$DB\'"',
        '  : > "$LOGS/known-modules.txt"',
    ]
    for version in env.chain():
        # The step's own add-ons path, so coverage asks exactly what the step
        # will be able to resolve — including the <= 13 fork layout.
        sources = " ".join(shlex.quote(str(p)) for p in env.coverage_dirs(version))
        apriori = shlex.quote(str(env.apriori_file(version)))
        custom = shlex.quote(str(env.addons_custom_dir(version)))
        decisions = shlex.quote(str(env.decisions_file))
        lines += [
            f"  # coverage: step {version}",
            f'  next_tsv=$(ODWG_MODULES_TSV="$modules_tsv" coverage_step {version} {apriori} '
            f'{custom} {decisions} {sources}) || blocking=1',
            # Kept even when the step reported blocking modules: the later steps
            # still have to be checked, and against the names they will use.
            '  if [ -n "$next_tsv" ]; then modules_tsv="$next_tsv"; fi',
        ]
    lines += [
        # The names the preflight accounted for. A step judges what is *not*
        # here — a module the chain installed along the way, which the source
        # database never had. Anything already accounted for reaches the same
        # verdict twice, so judging it again buys nothing and only widens what a
        # gate lets through.
        '  printf \'%s\\n\' "$modules_tsv" | cut -f1 > "$LOGS/known-modules.txt"',
        '  [ "$blocking" = 0 ] || fail "addons coverage incomplete (see [coverage] lines above)"',
        '  echo "[preflight] database checks passed"',
        "}",
    ]
    return "\n".join(lines)


def render_run_migration_sh(env: MigrationEnv) -> str:
    """The checkpointing driver: preflight the host, restore a source dump into a
    working DB (verifying it before step 1), then run each step in order, dumping
    a checkpoint after each success (never touches the source/production database).

    A re-run resumes from the last good step: the working DB is restored from the
    newest checkpoint before the first pending step, because a failed step leaves
    it half-migrated (OpenUpgrade commits module by module). The run is bound to
    one source dump by its SHA-256, so a different dump is refused instead of
    silently ignored."""
    header = f"""#!/usr/bin/env bash
# Generated by odoo_dwg — OpenUpgrade migration {env.source} -> {env.target}.
set -euo pipefail

SRC_DUMP="${{1:?usage: run_migration.sh <source-db-custom-format-dump> [--redo-modules]}}"
# --redo-modules: run the client-modules stage again, from the target checkpoint.
REDO_MODULES=0
case "${{2:-}}" in
  "") ;;
  --redo-modules) REDO_MODULES=1 ;;
  *) echo "usage: run_migration.sh <source-db-custom-format-dump> [--redo-modules]" >&2; exit 2 ;;
esac
MODULES_CK={shlex.quote(modules_stage(env))}
MODULES_PLAN={shlex.quote(str(env.logs_dir / f"{modules_stage(env)}-plan.json"))}
# Present while the client-modules stage has changed the working database without a
# checkpoint of its own: the stage then starts again from the target checkpoint.
MODULES_DIRTY={shlex.quote(str(env.checkpoints_dir / f"{modules_stage(env)}.dirty"))}
# Whether the working database is known to be exactly at the target checkpoint.
AT_TARGET=0
DB={shlex.quote(env.database)}
export PGHOST={shlex.quote(env.db_host)} PGPORT={int(env.db_port)} PGUSER={shlex.quote(env.db_user)}
CK={shlex.quote(str(env.checkpoints_dir))}
LOGS={shlex.quote(str(env.logs_dir))}
# A checkpoint is a dump of the restored copy of a customer's production
# database, and a log is Odoo's log for it: neither is for other accounts on this
# host to read, whatever the operator's umask and home directory allow.
umask 077
mkdir -p "$CK" "$LOGS"
chmod 700 "$CK" "$LOGS"

fail() {{ echo "[preflight-fail] $1" >&2; exit 1; }}
die() {{ echo "[fail] $1" >&2; exit 1; }}

{_render_preflight_host(env)}

{_render_preflight_db(env)}

# One line per event, appended and never rewritten: a run killed mid-step still
# leaves a readable record, and a watcher can tail it while the chain runs. The
# timestamp is what `journalctl --since/--until` takes, so a step's window can be
# handed to the firewall's journal without guessing where the step began.
#   <when>\t<run>\t<step>\t<event>\t<detail>
STEPS="$LOGS/steps.tsv"
mark() {{ printf '%s\t%s\t%s\t%s\t%s\n' "$(date -Is)" "${{SRC_SHA:0:12}}" "$1" "$2" "${{3:-}}" >> "$STEPS"; }}

have_ck() {{ [ -f "$CK/$1.dump" ]; }}
# Written through a temp file: an interrupted dump must never look like a
# finished checkpoint the next run would trust.
checkpoint() {{
  # Explicitly, not as a && b || c: a failing pg_dump must abort the run instead
  # of leaving an empty .tmp behind while the step reports success.
  if ! pg_dump -Fc "$DB" > "$CK/$1.dump.tmp"; then
    rm -f "$CK/$1.dump.tmp"
    die "checkpoint $1 could not be written"
  fi
  mv "$CK/$1.dump.tmp" "$CK/$1.dump" || die "checkpoint $1 could not be saved"
  echo "[checkpoint] $1"
}}

# Every database this driver leaves behind — each checkpoint, and the migrated one —
# is neutralised: crons off but housekeeping, mail captured, tax, EDI, payment and
# online services out of production, every change recorded inside the database.
# Re-applied at every point, because a step's module updates switch crons back on.
# Nothing here gives production's settings back: that is the operator's action.
NEUTRALISE={shlex.quote(str(env.root / NEUTRALISE_FILE))}
NEUTRAL_CHECK={shlex.quote(str(env.root / NEUTRAL_CHECK_FILE))}
neutralise() {{
  if [ ! -f "$NEUTRALISE" ] || [ ! -f "$NEUTRAL_CHECK" ]; then
    echo "[warn] $NEUTRALISE is missing — regenerate this environment. '$DB' is NOT neutralised." >&2
    return 0
  fi
  psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f "$NEUTRALISE" >/dev/null \\
    || die "could not neutralise '$DB' ($1)"
  psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f "$NEUTRAL_CHECK" >/dev/null \\
    || die "'$DB' can still act on the outside after neutralising ($1)"
  echo "[neutralise] $1"
  mark - neutralised "$1"
}}

preflight_host
{_render_driver_filestore(env)}
{_render_step_hook(env)}
restore_ck() {{
  echo "[init] restoring checkpoint $1 into working DB '$DB'"
  dropdb --if-exists "$DB"
  createdb "$DB"
  give_filestore
  pg_restore --no-owner --dbname "$DB" "$CK/$1.dump"
  neutralise "$1"
}}

SRC_SHA=$(sha256sum "$SRC_DUMP" | cut -d' ' -f1)
mark - run-start "{env.source} -> {env.target}"
if ! have_ck 00_source; then
  # A fresh run owns the checkpoint directory: step dumps left by an earlier run
  # belong to another attempt and would be skipped as if they were this one's.
  rm -f "$CK"/*.dump "$CK"/*.dump.tmp "$CK"/*.dirty "$CK/source.sha256"
  mark - restore 00_source
  echo "[init] restoring source dump into working DB '$DB'"
  dropdb --if-exists "$DB"
  createdb "$DB"
  give_filestore
  pg_restore --no-owner --dbname "$DB" "$SRC_DUMP"
  preflight_db
  neutralise 00_source
  echo "$SRC_SHA" > "$CK/source.sha256.tmp" && mv "$CK/source.sha256.tmp" "$CK/source.sha256"
  checkpoint 00_source
else
  # Three states, not two: recorded and equal, recorded and different, or not
  # recorded at all. Calling the third one "another source dump" was false, and
  # the remedy it named threw away every completed step of the chain.
  CK_SHA=$(cat "$CK/source.sha256" 2>/dev/null || true)
  if [ -z "$CK_SHA" ]; then
    die "the checkpoints in $CK do not record which dump they came from.
  If they came from $SRC_DUMP, adopt them with:
    sha256sum \\"$SRC_DUMP\\" | cut -d' ' -f1 > \\"$CK/source.sha256\\"
  If they came from another dump, remove $CK to start over."
  elif [ "$CK_SHA" != "$SRC_SHA" ]; then
    die "checkpoints in $CK came from another source dump — remove that whole directory to start over"
  fi
  if [ "$REDO_MODULES" = 1 ]; then
    # The working database holds the stage's result: the stage restores the target first.
    if have_ck "$MODULES_CK"; then
      rm -f "$CK/$MODULES_CK.dump"
      : > "$MODULES_DIRTY"
    fi
    echo "[init] --redo-modules: the client-modules stage runs again"
  fi
  # A failed step leaves the working DB half-migrated: resume from the newest
  # checkpoint, not from whatever the DB holds now.
  LAST=00_source
  gap=0
  for step in {' '.join(env.chain())}; do
    if [ "$gap" = 0 ] && have_ck "$step"; then
      LAST="$step"
    else
      # Past the first gap nothing is trustworthy: those dumps came from another
      # attempt, and a step after a gap would run on the wrong database.
      gap=1
      rm -f "$CK/$step.dump"
    fi
  done
  # The client-modules stage comes after the target step, and follows the same rule.
  if [ "$gap" = 0 ] && have_ck "$MODULES_CK"; then
    LAST="$MODULES_CK"
  else
    rm -f "$CK/$MODULES_CK.dump"
  fi
  if [ "$LAST" = "{env.target}" ] || [ "$LAST" = "$MODULES_CK" ]; then
    echo "[init] every step already has a checkpoint"
  else
    mark - restore "$LAST"
    restore_ck "$LAST"
  fi
fi
"""
    steps: list[str] = []
    for version in env.chain():
        layout = "legacy layout" if env.uses_legacy_layout(version) else "upgrade-path layout"
        steps.append(
            f"""
# --- step: upgrade to {version} ({layout}) ---
if have_ck "{version}"; then
  echo "[skip] {version} already migrated"
  mark "{version}" skip
else
  echo "[step] upgrading to {version} ({layout})"
  mark "{version}" start
{_render_step_preconditions(env, version)}  step_hook "{version}" pre
  code=0
  {_native_step_command(env, version)} || code=$?
  # `|| code=$?`, not `if ! cmd; then code=$?`: inside the negation `$?` is the
  # status of *not having failed*, which is 0, so every failure was recorded as
  # exit 0 — verified by running the driver against a failing step.
  if [ "$code" -ne 0 ]; then
    mark "{version}" fail "$code"
    die "step {version} failed — see {env.logs_dir}/{version}.log"
  fi
  step_hook "{version}" post
{_render_step_repair(env, version)}  neutralise "{version}"
  checkpoint "{version}"
  mark "{version}" ok
fi"""
        )
    # The target step just ran, or was skipped: only when it ran is the working database
    # known to be exactly at the target checkpoint.
    done = f'  mark "{env.target}" ok\nfi'
    if not steps[-1].endswith(done):
        raise AssertionError("the target step no longer ends where AT_TARGET is set")
    steps[-1] = steps[-1][: -len(done)] + (f'  mark "{env.target}" ok\n  AT_TARGET=1\n  rm -f "$MODULES_DIRTY"\nfi')
    steps.append(_render_modules_stage(env))
    footer = (
        '\n\nmark - run-ok\n'
        f'echo "[done] migration complete — working DB is now Odoo {env.target}"\n'
    )
    return header + "".join(steps) + footer


#: The environment's neutralisation, as the driver and ``open_for_testing.sh`` run it.
NEUTRALISE_FILE = "neutralise.sql"
NEUTRAL_CHECK_FILE = "neutralise_check.sql"
#: Where ``open_for_testing.sh`` serves Odoo, and so where a neutralised copy's links point.
OPEN_HTTP_PORT = 8069


def render_neutralise_sql() -> str:
    """Mail capture, then the rest of the catalogue: what ``plan_neutralise`` runs."""
    return (
        "-- Generated by odoo_dwg. Neutralises a copy of production, recording every change\n"
        "-- inside the database; repeatable. Giving production's settings back is the\n"
        "-- operator's explicit menu action, never this file.\n"
        f"{egress.mail_capture_sql()}\n"
        f"{neutralise.apply_sql(f'http://127.0.0.1:{OPEN_HTTP_PORT}')}\n"
    )


def render_neutral_check_sql() -> str:
    """Raises, naming what can still act on the outside; writes nothing."""
    guard = neutralise.guard_sql(f"http://127.0.0.1:{OPEN_HTTP_PORT}",
                                 (egress.MAILPIT_SMTP_HOST, egress.MAILPIT_SMTP_PORT))
    return (
        "-- Generated by odoo_dwg. Fails, naming each rule, if anything in the database can\n"
        f"-- still act on the outside. Writes nothing.\n{guard}\n"
    )


def render_open_for_testing_sh(env: MigrationEnv) -> str:
    """Start Odoo on a database of this migration, neutralised, with no cron thread.

    The one way this environment offers to open a migrated database or a
    checkpoint: every start re-neutralises (an install or update since the last
    one may have switched crons back on) and refuses to start if anything can
    still act; ``--max-cron-threads=0`` keeps a cron a module installs during the
    session from running before the next start turns it off."""
    q = shlex.quote
    source = (f"  {env.source}) PY={q(str(env.venv_dir(env.source) / 'bin' / 'python'))}; "
              f"BIN={q(str(env.source_odoo_bin))}; CONF={q(str(env.config_file(env.source)))} ;;")
    cases = "\n".join([source] + [
        f"  {version}) PY={q(str(env.venv_dir(version) / 'bin' / 'python'))}; "
        f"BIN={q(str(env.odoo_bin(version)))}; CONF={q(str(env.config_file(version)))} ;;"
        for version in env.chain()
    ])
    versions = " ".join([env.source, *env.chain()])
    reference = env.intake.reference_database if env.intake is not None else ""
    # The reference is what every copy is taken from: never opened, never neutralised.
    guard_reference = (
        f'[ "$DB" != {q(reference)} ] || die "{reference} is the reference, which nothing '
        f'modifies — open a copy of it instead"\n' if reference else "")
    # A copy needs its own filestore: Odoo looks in filestore/<database>. Hard links
    # take no space, and Odoo never rewrites an attachment file in place.
    filestore = (
        f'if [ ! -e "$DATA/filestore/$DB" ] && [ -d "$DATA/filestore/"{q(reference)} ]; then\n'
        f'  cp -al "$DATA/filestore/"{q(reference)} "$DATA/filestore/$DB" \\\n'
        f'    || die "could not give \'$DB\' a filestore"\n'
        f'  echo "[filestore] $DB: hard links to {reference}\'s attachments"\n'
        f"fi\n" if reference else "")
    return f"""#!/usr/bin/env bash
# Generated by odoo_dwg — open a database of the {env.source} -> {env.target} migration for testing.
# Every start re-neutralises it and refuses to start if anything can still act on the
# outside; Odoo then runs with no cron thread, on loopback only, its mail to the capture.
# There is no option to skip either. Giving production's settings back is the menu's
# explicit action ("Give a neutralised database its production settings back"), never this.
set -euo pipefail

usage="usage: open_for_testing.sh <version: {versions}> <database>"
VERSION="${{1:?$usage}}"
DB="${{2:?$usage}}"
export PGHOST={q(env.db_host)} PGPORT={int(env.db_port)} PGUSER={q(env.db_user)}
NEUTRALISE={q(str(env.root / NEUTRALISE_FILE))}
NEUTRAL_CHECK={q(str(env.root / NEUTRAL_CHECK_FILE))}
DATA={q(str(env.data_dir))}

die() {{ echo "[fail] $1" >&2; exit 1; }}

[[ "$DB" =~ ^[a-zA-Z0-9][a-zA-Z0-9_.-]+$ ]] || die "not a database name: $DB"
{guard_reference}case "$VERSION" in
{cases}
  *) die "$VERSION is not a version of this chain ({versions})" ;;
esac
[ -f "$NEUTRALISE" ] && [ -f "$NEUTRAL_CHECK" ] \\
  || die "$NEUTRALISE is missing — regenerate this environment"
[ -f "$CONF" ] || die "$CONF is missing — build Odoo $VERSION first"

echo "[neutralise] $DB"
psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f "$NEUTRALISE" >/dev/null \\
  || die "could not neutralise '$DB'; not starting"
psql -X -q -v ON_ERROR_STOP=1 -d "$DB" -f "$NEUTRAL_CHECK" >/dev/null \\
  || die "'$DB' can still act on the outside; not starting"

mkdir -p "$DATA"
{filestore}echo "[start] Odoo $VERSION on http://127.0.0.1:{OPEN_HTTP_PORT} — no cron thread, mail to the capture"
exec "$PY" "$BIN" -c "$CONF" -d "$DB" --db-filter="^${{DB}}\\$" --data-dir="$DATA" \\
  --http-interface=127.0.0.1 --http-port={OPEN_HTTP_PORT} --max-cron-threads=0 --workers=0
"""


#: Who the generated tester is by. Declared, because Odoo attributes a manifest
#: without an author to "Odoo S.A." and that is not true of this one.
TESTER_AUTHOR = "odoo_dwg"


def render_tester_module(probes: list, uncovered: list[str], chain: str) -> dict[str, str]:
    """The rehearsal tester add-on, as ``relative path -> content``.

    Declaration-only by design: it depends on ``base`` alone and refers to no
    subject in code, so it installs on the source version whatever the chain
    contains. What it carries is one row per probe.
    """
    return {
        "__init__.py": "from . import models\n",
        "models/__init__.py": "from . import probe\n",
        "models/probe.py": _render_probe_model(),
        "security/ir.model.access.csv": (
            "id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink\n"
            f"access_{tester.PROBE_TABLE},{tester.PROBE_MODEL},"
            f"model_{tester.PROBE_TABLE},,1,0,0,0\n"
        ),
        "data/probes.xml": _render_probe_data(probes),
        "__manifest__.py": _render_tester_manifest(probes, uncovered, chain),
    }


def _render_probe_model() -> str:
    """Written for Odoo 12 to 19 alike: `from odoo import fields, models`, a
    `_description`, and no field type that arrived mid-chain."""
    return (
        "# Generated by odoo_dwg. Rehearsal instrument — see the manifest.\n"
        "from odoo import fields, models\n"
        "\n"
        "\n"
        "class MigrationProbe(models.Model):\n"
        f"    _name = {tester.PROBE_MODEL!r}\n"
        '    _description = "odoo_dwg migration probe"\n'
        "\n"
        "    name = fields.Char(required=True, index=True)\n"
        "    kind = fields.Char(required=True)\n"
        "    step = fields.Char(required=True)\n"
        "    subject_model = fields.Char(required=True)\n"
        "    subject_field = fields.Char()\n"
        "    successor = fields.Char()\n"
        "    expected_gone = fields.Boolean()\n"
        "    source_line = fields.Text()\n"
    )


def _render_probe_data(probes: list) -> str:
    """One record per probe. `noupdate` so a step's `-u all` cannot rewrite what
    the source version recorded — the record is the evidence."""
    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        "<!-- Generated by odoo_dwg. One record per declared expectation. -->",
        "<odoo>",
        '  <data noupdate="1">',
    ]
    for probe in probes:
        lines += [
            f'    <record id="{escape(probe.name)}" model="{tester.PROBE_MODEL}">',
            f'      <field name="name">{escape(probe.name)}</field>',
            f'      <field name="kind">{escape(probe.kind)}</field>',
            f'      <field name="step">{escape(probe.version)}</field>',
            f'      <field name="subject_model">{escape(probe.model)}</field>',
            f'      <field name="subject_field">{escape(probe.field)}</field>',
            f'      <field name="successor">{escape(probe.successor)}</field>',
            f'      <field name="expected_gone" '
            f'eval="{"True" if probe.expected_gone else "False"}"/>',
            # The analysis file's own words: a probe that paraphrased its source
            # would make its own claim unverifiable.
            # Tabs out: the check reads these rows tab-separated, and an
            # analysis line holding one would split into a probe that is not there.
            f'      <field name="source_line">'
            f'{escape(probe.detail.replace(chr(9), " "))}</field>',
            "    </record>",
        ]
    lines += ["  </data>", "</odoo>", ""]
    return "\n".join(lines)


def _render_tester_manifest(probes: list, uncovered: list[str], chain: str) -> str:
    """No menu, no group, no `auto_install`: installing it by accident changes
    nothing a user sees."""
    covered = sorted({probe.kind for probe in probes})
    summary = (
        f"odoo_dwg rehearsal instrument for the {chain} chain — declares what the "
        "OpenUpgrade sources predict, so a step can be asked what it took away. "
        "Not for a production database."
    )
    description = "\n".join(
        [
            f"Generated by odoo_dwg for the {chain} chain.",
            "",
            "Each record of odwg.migration.probe names one upstream subject, the class of",
            "change its step's analysis file declares, and that file's own line.",
            "",
            f"Classes covered ({len(covered)}): " + ", ".join(covered) or "none",
            f"Classes this chain never exercises ({len(uncovered)}): "
            + (", ".join(uncovered) or "none"),
        ]
    )
    return (
        "# Generated by odoo_dwg. Regenerate rather than edit.\n"
        "{\n"
        f'    "name": "odoo_dwg migration tester ({chain})",\n'
        '    "version": "1.0.0",\n'
        '    "category": "Technical",\n'
        # Odoo defaults a manifest with no `author` to "Odoo S.A."
        # (`load_information_from_description_file`). Left out, this module is
        # attributed to Odoo in `ir_module_module`, which is false — and coverage
        # reads that column to decide whether a missing module is Odoo's own
        # dropped code (a warning) or somebody else's (blocking), so the omission
        # also downgraded its own absence to a warning.
        f'    "author": "{TESTER_AUTHOR}",\n'
        '    "license": "LGPL-3",\n'
        f'    "summary": {summary!r},\n'
        f'    "description": """{description}""",\n'
        '    "depends": ["base"],\n'
        '    "data": ["security/ir.model.access.csv", "data/probes.xml"],\n'
        '    "installable": True,\n'
        '    "application": False,\n'
        "}\n"
    )


def render_seed_conf(env: MigrationEnv) -> str:
    """``odoo.conf`` for the source version a demo seed is built on.

    Plain Odoo, not an OpenUpgrade step: the add-ons path is the source's own
    (`source_addons_path`), and mail goes to the local capture like every other
    config this tool writes — demo data contains addresses.
    """
    return "\n".join(
        [
            "[options]",
            f"; Generated by odoo_dwg — demo seed for Odoo {env.source}.",
            f"addons_path = {env.source_addons_path}",
            "",
            f"db_host = {env.db_host}",
            f"db_port = {env.db_port}",
            f"db_user = {env.db_user}",
            "",
            "workers = 0",
            "max_cron_threads = 0",
            # With an intake, the client's filestore lives under the environment.
            *([f"data_dir = {env.data_dir}"] if env.intake is not None else []),
            "",
            *_smtp_to_capture(),
        ]
    ) + "\n"


def render_seed_demo_sh(env: MigrationEnv, modules: list[str]) -> str:
    """Build a demo database at the source version and dump it for the driver.

    Installed one module at a time, not in one ``-i a,b,c``: Odoo stops at the
    first failure and reports it, and with a single call the operator is told
    only that *something* did not install. One at a time names which — and the
    script stops there rather than dumping a database missing a module the
    rehearsal was meant to exercise.

    The demo flag is **not** passed, and that is the verified answer rather than
    an omission. In 12.0 to 18.0 `--without-demo` carries `my_default=False`
    (`odoo/tools/config.py`), so a database created with `-i` gets Odoo's demo
    data unless the flag disables it. 19.0 rewrote the option — `dest="with_demo"`,
    `type='without_demo'`, and its help now reads "don't install demo data in new
    databases (default)" — so there the default is the opposite. A chain's source
    is always <= 18.0 (`migration_chain` requires source < target <= 19.0), so
    omitting the flag is right for every source this tool accepts; a 19.0 source
    would have to ask for demo data explicitly, and cannot occur.
    """
    q = shlex.quote
    venv = env.venv_dir(env.source)
    odoo_bin = env.source_odoo_bin
    conf = env.config_file(env.source)
    log = env.logs_dir / f"seed-{env.source}.log"
    database = env.source_database
    dump = env.source_dump_file
    run = f'{q(f"{venv}/bin/python")} {q(str(odoo_bin))} -c {q(str(conf))} -d {q(database)}'
    lines = [
        "#!/bin/bash",
        "# Generated by odoo_dwg. Builds a demo source database and dumps it.",
        "set -euo pipefail",
        "",
        'die() { echo "[fail] $*" >&2; exit 1; }',
        "",
        f'DB={q(database)}',
        f'DUMP={q(str(dump))}',
        f'LOG={q(str(log))}',
        "",
        '[ -x "$(command -v createdb)" ] || die "createdb not on PATH"',
        f'[ -x {q(f"{venv}/bin/python")} ] || die "no venv for Odoo {env.source}: generate the environment first"',
        f'[ -r {q(str(odoo_bin))} ] || die "no Odoo {env.source} clone: generate the environment first"',
        "",
        '# A dump the driver may already have checkpoints against is not replaced',
        '# silently; the caller confirms and removes it.',
        '[ -e "$DUMP" ] && die "$DUMP exists — remove it to seed again"',
        "",
        # The same connection every other command here uses. Without -h/-U this
        # connects as the OS user over the default socket, fails with "role does
        # not exist", and the pipeline quietly yields nothing — so the check
        # never found an existing database on a real host.
        f'if psql -X -w -h {q(env.db_host)} -p {int(env.db_port)} -U {q(env.db_user)} '
        '-lqt | cut -d\\| -f1 | grep -qw "$DB"; then',
        '  die "database $DB exists — drop it to seed again"',
        "fi",
        'echo "[init] creating $DB"',
        f'createdb -h {q(env.db_host)} -p {int(env.db_port)} -U {q(env.db_user)} "$DB"',
        "",
        # `base` with demo data first: the flag is only read when the database is
        # initialised, so every later module inherits the demo set.
        'echo "[step] installing base with demo data"',
        f'{run} -i base --stop-after-init --logfile="$LOG" '
        '|| die "base did not install — see $LOG"',
    ]
    for module in modules:
        lines += [
            f'echo "[step] installing {module}"',
            f'{run} -i {q(module)} --stop-after-init --logfile="$LOG" '
            f'|| die "{module} did not install — see $LOG"',
        ]
    lines += [
        "",
        'echo "[step] dumping $DB"',
        # -Fc: the format run_migration.sh requires, and the one it checks for.
        # Written beside the target and renamed: a dump interrupted halfway is not
        # a dump, and one left under the real name would be taken for one by the
        # next seed and by the driver.
        f'pg_dump -h {q(env.db_host)} -p {int(env.db_port)} -U {q(env.db_user)} '
        '-Fc -f "$DUMP.tmp" "$DB" || { rm -f "$DUMP.tmp"; die "pg_dump failed"; }',
        'mv -f "$DUMP.tmp" "$DUMP"',
        'echo "[done] $DUMP"',
        'echo "Run the chain with: ./run_migration.sh $DUMP"',
        "",
    ]
    return "\n".join(lines)
