"""Pure text builders for every generated workspace artifact.

Standard-library only, no I/O: each function returns the exact file *content* as a
string, so tests can assert on the rendered text and planners can wrap it in a
``write_text_file_command``. All generated artifacts are **English** (they are
technical and portable); the app's own UI is what gets translated, not these.

Odoo config keys, ``addons_path`` composition, and the source-install flow are
anchored to the official Odoo "Source install" and CLI / ``odoo.conf`` reference
pages (see docs/).
"""

from __future__ import annotations

import json

from .models import (
    LEGACY_LAYOUT_MAX_MAJOR,
    UV_PYTHON,
    InstanceConfig,
    InterpreterChoice,
    MigrationEnv,
    WorkspaceConfig,
    migration_interpreter,
    odoo_major,
    version_support,
)


def _gevent_port_key(version: str) -> str:
    """Live-chat/bus port key: ``gevent_port`` on Odoo ≥ 16, else ``longpolling_port``."""
    return "gevent_port" if odoo_major(version) >= 16 else "longpolling_port"


def render_odoo_conf(cfg: WorkspaceConfig, version: str) -> str:
    """Render a development ``odoo.conf`` for one instance of the workspace.

    Development posture: ``workers = 0`` (threaded, debugger-friendly), the
    composed ``addons_path``, the derived per-version HTTP port, and a separate
    bus port. Keys are the official ``odoo.conf`` options.
    """
    http_port = cfg.http_port_for(version)
    bus_port = http_port + 1000
    lines = [
        "[options]",
        "; Generated by odoo_dwg — development configuration.",
        f"addons_path = {cfg.addons_path(version)}",
        "",
        "http_interface = 127.0.0.1",
        f"http_port = {http_port}",
        f"{_gevent_port_key(version)} = {bus_port}",
        "",
        "; Development posture: threaded mode so the debugger can attach.",
        "workers = 0",
        "max_cron_threads = 1",
        "dev_mode = reload,qweb,xml",
        "",
        f"db_host = {cfg.db_host}",
        f"db_port = {cfg.db_port}",
        f"db_user = {cfg.db_user}",
        "admin_passwd = admin",
    ]
    return "\n".join(lines) + "\n"


def render_setup_venv_sh(
    cfg: WorkspaceConfig,
    interpreters: dict[str, InterpreterChoice] | None = None,
) -> str:
    """A reproducible bash script that (re)builds every instance venv and installs
    its version-matched requirements from the shared repo cache.

    ``interpreters`` must be the same resolved choices the generation plan used:
    a version whose venv the plan builds with a ``uv``-provided interpreter has to
    be rebuilt the same way here, or re-running this script would quietly replace
    it with the host ``python3`` — the exact breakage the support matrix exists to
    prevent."""
    header = [
        "#!/usr/bin/env bash",
        "# Generated by odoo_dwg — create/refresh the per-version virtualenvs.",
        "set -euo pipefail",
        "",
        f'WORKSPACE="{cfg.root}"',
        f'REPOS="{cfg.repos_dir}"',
        "",
    ]
    blocks: list[str] = []
    for inst in cfg.instances():
        venv = cfg.venv_dir(inst.version)
        odoo = cfg.odoo_clone_dir(inst.version)
        choice = (interpreters or {}).get(inst.version)
        if choice and choice.source == UV_PYTHON and choice.python:
            create = [
                f'# Odoo {inst.version} supports Python {version_support(inst.version).python_range_text()}',
                f'uv venv --seed --no-project --python {choice.python} "{venv}"',
            ]
        else:
            create = [f'python3 -m venv "{venv}"']
        blocks.append(
            "\n".join(
                [
                    f'echo "[odoo{inst.major}] creating venv {venv}"',
                    *create,
                    f'"{venv}/bin/pip" install --upgrade pip wheel setuptools',
                    f'"{venv}/bin/pip" install -r "{odoo}/requirements.txt"',
                    "",
                ]
            )
        )
    return "\n".join(header + blocks)


def render_run_sh(cfg: WorkspaceConfig, version: str) -> str:
    """A bash launcher for one instance (venv python + odoo-bin + its conf)."""
    inst = InstanceConfig(cfg.name, version)
    venv = cfg.venv_dir(version)
    odoo = cfg.odoo_clone_dir(version)
    conf = cfg.config_file(version)
    return "\n".join(
        [
            "#!/usr/bin/env bash",
            f"# Generated by odoo_dwg — run the {inst.name} instance.",
            "set -euo pipefail",
            f'exec "{venv}/bin/python" "{odoo}/odoo-bin" -c "{conf}" "$@"',
            "",
        ]
    )


def render_vscode_settings(cfg: WorkspaceConfig) -> str:
    default = cfg.versions[0]
    settings = {
        "python.defaultInterpreterPath": str(cfg.venv_dir(default) / "bin" / "python"),
        "python.terminal.activateEnvironment": True,
        # The official Odoo language server analyses Python; Pylance doing the
        # same would duplicate (and contradict) its diagnostics. The Python
        # extension stays for debugging and interpreter selection.
        "python.languageServer": "None",
        "files.exclude": {"**/__pycache__": True, "**/*.pyc": True},
        "search.exclude": {"**/.venv": True, "**/.repos": True},
    }
    return json.dumps(settings, indent=2) + "\n"


# The official Odoo extension and the language server it runs (odoo/odoo-vscode,
# odoo/odoo-ls). See docs/editor-integration.md for the update procedure.
ODOO_EXTENSION_ID = "Odoo.odoo"

# The OdooLS release this configuration was last reviewed against. Bump it in
# the change that adopts what a review of newer releases found, never alone:
# tools/verify_odools_config.py reports the release notes since this version.
ODOOLS_REVIEWED_VERSION = "1.4.0"

# The only keys emitted per profile: the "minimal config file" of the OdooLS
# documentation. The schema is strict (additionalProperties: false), so an
# unknown key breaks the whole file; these four are in every stable schema on
# record. Keys documented as applying from a given release (the 1.5 JavaScript
# options, semantic-token switches) and template variables are deliberately
# never emitted — they are exactly what changes between releases.
ODOOLS_KEYS: tuple[str, ...] = ("name", "odoo_path", "addons_paths", "python_path")

# OdooLS refuses Odoo below this major ("only supports version 14 and above").
ODOOLS_MIN_ODOO_MAJOR = 14


def odools_versions(cfg: WorkspaceConfig) -> list[str]:
    """The workspace versions the official language server can open."""
    return [v for v in cfg.versions if odoo_major(v) >= ODOOLS_MIN_ODOO_MAJOR]


def _toml_string(value: str) -> str:
    """A TOML basic string. JSON's string escaping is a valid subset of TOML's
    (backslash, quote, control characters, \\uXXXX), so it quotes paths safely."""
    return json.dumps(value, ensure_ascii=False)


def render_odools_toml(cfg: WorkspaceConfig) -> str:
    """The official Odoo language server's configuration: one profile per version.

    The workspace opens only its own root while Odoo lives in the shared cache
    outside it — often in several versions — so OdooLS's zero-config detection
    cannot find it. Each profile states the four facts the generator already
    knows, as absolute paths. Core add-ons are loaded by OdooLS from
    ``odoo_path``, so ``addons_paths`` lists the workspace's own directories only."""
    lines = [
        "# Generated by odoo_dwg — profiles for the official Odoo language server",
        f"# (OdooLS, reviewed against {ODOOLS_REVIEWED_VERSION}). Pick one from the status bar.",
        "# Only the documented minimal keys are set; add your own below if you need more.",
    ]
    skipped = [v for v in cfg.versions if v not in odools_versions(cfg)]
    if skipped:
        lines.append(
            f"# No profile for {', '.join(skipped)}: OdooLS supports Odoo "
            f"{ODOOLS_MIN_ODOO_MAJOR} and above only."
        )
    for inst in cfg.instances():
        if inst.version not in odools_versions(cfg):
            continue
        addons = ", ".join(
            _toml_string(str(path)) for path in cfg.addons_dirs(inst.version, include_core=False)
        )
        values = {
            "name": _toml_string(f"{cfg.name} {inst.version}"),
            "odoo_path": _toml_string(str(cfg.odoo_clone_dir(inst.version))),
            "addons_paths": f"[{addons}]",
            "python_path": _toml_string(str(cfg.venv_dir(inst.version) / "bin" / "python")),
        }
        lines += ["", "[[config]]"] + [f"{key} = {values[key]}" for key in ODOOLS_KEYS]
    return "\n".join(lines) + "\n"


def render_vscode_extensions() -> str:
    recommendations = {
        "recommendations": [
            "ms-python.python",
            "ms-python.debugpy",
            ODOO_EXTENSION_ID,
        ]
    }
    return json.dumps(recommendations, indent=2) + "\n"


def render_vscode_tasks(cfg: WorkspaceConfig) -> str:
    tasks = {
        "version": "2.0.0",
        "tasks": [
            {
                "label": "Setup venvs",
                "type": "shell",
                "command": "bash scripts/setup_venv.sh",
                "problemMatcher": [],
            }
        ]
        + [
            {
                "label": f"Run odoo{odoo_major(v)}",
                "type": "shell",
                "command": f"bash scripts/run-odoo{odoo_major(v)}.sh",
                "problemMatcher": [],
            }
            for v in cfg.versions
        ],
    }
    return json.dumps(tasks, indent=2) + "\n"


def render_vscode_launch(cfg: WorkspaceConfig) -> str:
    configurations = []
    for inst in cfg.instances():
        configurations.append(
            {
                "name": f"Odoo {inst.version} ({inst.name})",
                "type": "debugpy",
                "request": "launch",
                "python": str(cfg.venv_dir(inst.version) / "bin" / "python"),
                "program": str(cfg.odoo_clone_dir(inst.version) / "odoo-bin"),
                "args": ["-c", str(cfg.config_file(inst.version))],
                "console": "integratedTerminal",
                "justMyCode": False,
            }
        )
    return json.dumps({"version": "0.2.0", "configurations": configurations}, indent=2) + "\n"


def render_code_workspace(cfg: WorkspaceConfig) -> str:
    workspace = {
        "folders": [{"path": "."}],
        "settings": {"python.terminal.activateEnvironment": True},
    }
    return json.dumps(workspace, indent=2) + "\n"


def render_workspace_readme(cfg: WorkspaceConfig) -> str:
    """A robust per-workspace README giving any human or AI full context —
    versions, layout, per-version ports/configs, and setup/run commands."""
    version_rows = "\n".join(
        f"| {inst.version} | `{inst.name}` | {cfg.http_port_for(inst.version)} | "
        f"`config/odoo{inst.major}.conf` | `.venv/odoo{inst.major}` |"
        for inst in cfg.instances()
    )
    oca = ", ".join(cfg.oca_repos) if cfg.oca_repos else "(none)"
    # The language-server file only exists when OdooLS supports a version here.
    has_odools = bool(odools_versions(cfg))
    odools_line = (
        "\n├── odools.toml           # official Odoo language server profiles (Odoo >= 14)"
        if has_odools
        else ""
    )
    editor_hint = (
        " Install the recommended\nofficial Odoo extension (`Odoo.odoo`) and pick this workspace's profile for "
        "your version from the status\nbar (**Change Configuration**)."
        if has_odools
        else ""
    )
    return f"""# {cfg.name} — Odoo development workspace

Generated by **odoo_dwg**. This workspace hosts one Odoo Community instance per configured version, each with
its own virtualenv, config, and port. Odoo/OCA source lives in the shared cache at `{cfg.repos_dir}` and is
reused across workspaces.

## Versions

| Version | Instance | HTTP port | Config | Venv |
|---------|----------|-----------|--------|------|
{version_rows}

- OCA repositories: {oca}
- Custom addons: `addons-custom/` · OCA addons (symlinks): `addons-oca/`

## Layout

```
{cfg.name}/
├── addons-custom/        # your modules
├── addons-oca/           # symlinks into the shared OCA cache
├── config/odoo<major>.conf
├── .venv/odoo<major>/    # one venv per version
├── scripts/              # setup_venv.sh, run-odoo<major>.sh{odools_line}
└── {cfg.name}.code-workspace
```

## Setup & run

```bash
# From this workspace directory, on the Linux host:
bash scripts/setup_venv.sh          # create every venv + install requirements
bash scripts/run-odoo{cfg.instances()[0].major}.sh          # launch the {cfg.versions[0]} instance
```

Each instance's `addons_path` is composed of `addons-custom`, the OCA repos, then the shared Odoo `addons`.
Open `{cfg.name}.code-workspace` in VSCode for tasks and debug launch configs.{editor_hint}

The shared Odoo clones are shallow (no history). For `git log`/`git blame` on the Odoo source, run
`git -C {cfg.repos_dir}/odoo-<version> fetch --unshallow` once.
"""


# --- migration (F3) --------------------------------------------------------


# Overrides applied via ``uv pip install --overrides``: an entry replaces every
# requirement of the same package name during resolution (entries for packages the
# requirements never pull are ignored). Odoo branches 16/17/18 all pin
# gevent==21.8.0 for python_version == '3.10' (the Jammy assumption), but that
# release predates CPython 3.10 (no cp310 wheel) and its sdist no longer compiles
# under modern Cython. The official requirements' own pins for the 3.11 row —
# gevent==22.10.2 + greenlet==2.0.2 — ship cp310 wheels, so we lift to those.
_PY310_OVERRIDES = ("gevent==22.10.2", "greenlet==2.0.2")


def render_migration_overrides(version: str, python: str | None = None) -> str:
    """Per-version requirements repair for old branches, fed to ``--overrides``.

    Only the Python-3.10 steps need repairs today (see ``_PY310_OVERRIDES``);
    other interpreters resolve their branch's pins to installable wheels/sdists
    (validated on WSL: Odoo 15 on 3.8, Odoo 18 on 3.12).

    ``python`` is the interpreter the step will actually run, which differs from
    the matrix recommendation when the operator pinned the step; the repair must
    follow the interpreter in use, not the default one."""
    if python is None:
        python, _method = migration_interpreter(version)
    lines = [
        f"# Generated by odoo_dwg — requirements overrides for Odoo {version}"
        f" (Python {python})."
    ]
    if python == "3.10":
        lines.append("# gevent==21.8.0 has no cp310 wheel; lift to the branch's own 3.11 pins.")
        lines.extend(_PY310_OVERRIDES)
    return "\n".join(lines) + "\n"


def render_migration_scaffold(module: str, version: str, findings: list) -> str:
    """An additive ``pre-migration.py`` stub for one module/step: openupgradelib
    import plus one commented TODO per candidate finding. Inert until a developer
    reviews it — the header says so. ``findings`` are ``analysis.Finding``."""
    lines = [
        f"# Generated by odoo_dwg staging for {module} -> Odoo {version}.",
        "# REVIEW REQUIRED: these are CANDIDATE findings from the OpenUpgrade",
        "# analysis files — confirm each one, then implement and uncomment.",
        "# This stub does nothing until you complete it.",
        "from openupgradelib import openupgrade",
        "",
    ]
    for finding in findings:
        record = finding.record
        what = "model" if record.kind == "removed_model" else "field"
        lines.append(
            f"# TODO {record.model}: {what} '{record.name}' removed in {version}"
            f" (seen at {finding.path}:{finding.line})"
        )
    lines += [
        "",
        "",
        "@openupgrade.migrate()",
        "def migrate(env, version):",
        "    pass  # TODO: implement the reviewed operations above",
    ]
    return "\n".join(lines) + "\n"


def render_staging_report(module: str, steps: list[tuple[str, str, list, str | None]]) -> str:
    """The per-module staging report the developer works through. ``steps`` is
    ``(version, tool_log_text, findings, scaffold_path_or_None)`` per step; the
    tool's log is carried verbatim. States the boundary: staging is a prepared
    starting point, never a finished migration."""
    lines = [
        f"# Staging report — {module}",
        "",
        "Generated by odoo_dwg. **Staging is a prepared starting point: your review",
        "completes the migration.** Findings are candidates (name matches with the",
        "owning model present), not proof.",
        "",
    ]
    for version, log_text, findings, scaffold in steps:
        lines += [f"## Step {version}", "", "### odoo-module-migrate output (verbatim)", "```"]
        lines.append(log_text.rstrip() or "(no output captured)")
        lines += ["```", ""]
        if findings:
            lines.append("### Candidate findings (confirm each)")
            for finding in findings:
                record = finding.record
                what = "model" if record.kind == "removed_model" else "field"
                lines.append(
                    f"- `{record.model}` {what} `{record.name}` removed in {version}"
                    f" — seen at `{finding.path}:{finding.line}`"
                )
            lines.append("")
        else:
            lines += ["### Candidate findings", "None detected.", ""]
        if scaffold:
            lines += [f"Scaffold written: `{scaffold}` — review and complete it.", ""]
    return "\n".join(lines) + "\n"


def render_migration_conf(env: MigrationEnv, version: str) -> str:
    """Per-step ``odoo.conf`` for a migration step (no HTTP — runs stop-after-init)."""
    lines = [
        "[options]",
        f"; Generated by odoo_dwg — OpenUpgrade step to Odoo {version}.",
        f"addons_path = {env.addons_path(version)}",
        "",
        f"db_host = {env.db_host}",
        f"db_port = {env.db_port}",
        f"db_user = {env.db_user}",
        "",
        "workers = 0",
        "max_cron_threads = 0",
    ]
    return "\n".join(lines) + "\n"


def _native_step_command(env: MigrationEnv, version: str) -> str:
    """The command that upgrades the working database to one version.

    Two shapes, because OpenUpgrade changed layout at 14. From 14 the scripts sit
    under ``--upgrade-path`` and ``openupgrade_framework`` is loaded. Up to 13 they
    live inside each add-on and neither flag exists — that step runs the fork's own
    ``odoo-bin`` and depends entirely on the add-ons path reaching the fork's
    ``addons``. The path comes from the step's config file, which states it
    explicitly: an inherited or defaulted path that resolves to some other copy of
    Odoo's add-ons skips every add-on migration while the step still succeeds."""
    venv = env.venv_dir(version)
    conf = env.config_file(version)
    log = env.logs_dir / f"{version}.log"
    odoo_bin = env.odoo_bin(version)
    if env.uses_legacy_layout(version):
        return (
            f'"{venv}/bin/python" "{odoo_bin}" -c "{conf}" -d "$DB" '
            f'--update all --stop-after-init --logfile="{log}"'
        )
    scripts = env.upgrade_scripts_dir(version)
    return (
        f'"{venv}/bin/python" "{odoo_bin}" -c "{conf}" -d "$DB" '
        f'--upgrade-path="{scripts}" --update all --stop-after-init '
        f'--load=base,web,openupgrade_framework --logfile="{log}"'
    )


def render_migration_constraints(version: str) -> str | None:
    """Build constraints for a step whose dependencies a current toolchain cannot
    build as pinned, or ``None`` when the step needs none.

    Distinct from the requirements overrides: those change *what* is installed,
    these constrain the environment packages are *built* with. The 13.0 branch
    needs it because ``vatnumber==1.2`` still calls ``use_2to3``, which setuptools
    removed in 58."""
    if odoo_major(version) > LEGACY_LAYOUT_MAX_MAJOR:
        return None
    return (
        f"# Generated by odoo_dwg — build constraints for Odoo {version}.\n"
        "# vatnumber==1.2 uses use_2to3, removed in setuptools 58.\n"
        "setuptools<58\n"
    )


def _render_preflight_host(env: MigrationEnv) -> str:
    """Bash host-scope preflight: chain tools, PostgreSQL, dump integrity. The
    bash mirror of ``preflight.gather_host_facts`` (see design: the driver must
    stay plain bash, so the checks are rendered, kept in this one function)."""
    lines = [
        "preflight_host() {",
        '  command -v uv >/dev/null 2>&1 || fail "uv not found (needed for the native venvs)"',
    ]
    lines += [
        '  psql -tAc "SELECT 1" postgres >/dev/null 2>&1 || fail "PostgreSQL not reachable as $PGUSER@$PGHOST:$PGPORT"',
        '  [ -r "$SRC_DUMP" ] || fail "source dump not readable: $SRC_DUMP"',
        '  pg_restore --list "$SRC_DUMP" >/dev/null 2>&1 || fail "pg_restore cannot list $SRC_DUMP — a custom-format dump (pg_dump -Fc) is required"',
        '  echo "[preflight] host checks passed"',
        "}",
    ]
    return "\n".join(lines)


def _render_coverage_helper() -> str:
    """The bash+python helper the driver uses to judge one step's coverage.

    It applies the same rule as ``preflight.gather_coverage``: resolve what
    OpenUpgrade declares renamed or merged before calling anything missing, then
    split what is left by author — Odoo's own dropped code is a warning the
    upgrade handles, anybody else's is the operator's to supply. It reads
    ``apriori.py`` with ``ast`` at run time (never executing it), which is why
    nothing here needs the checkout at render time.

    Exits non-zero only when the blocking class is non-empty.
    """
    return "\n".join(
        [
            "coverage_step() {",
            '  local version="$1" apriori="$2" customdir="$3"; shift 3',
            "  python3 - \"$version\" \"$apriori\" \"$customdir\" \"$@\" <<'PYCOV'",
            "import ast, os, sys",
            "version, apriori, customdir, *sources = sys.argv[1:]",
            '# Exact spellings only: OCA authors contain "Odoo" and must not pass.',
            'ODOO_AUTHORS = {"odoo s.a.", "odoo sa", "openerp s.a.", "openerp sa", "odoo"}',
            "renames = {}",
            "try:",
            '    tree = ast.parse(open(apriori, encoding="utf-8").read())',
            "except (OSError, SyntaxError):",
            '    print("[coverage] %s: no readable apriori.py — renames unknown" % version,',
            "          file=sys.stderr)",
            "    tree = None",
            "if tree is not None:",
            "    for node in tree.body:",
            "        if not isinstance(node, ast.Assign):",
            "            continue",
            "        names = {t.id for t in node.targets if isinstance(t, ast.Name)}",
            '        if not names & {"renamed_modules", "merged_modules"}:',
            "            continue",
            "        try:",
            "            value = ast.literal_eval(node.value)",
            "        except ValueError:",
            "            continue",
            "        if isinstance(value, dict):",
            "            renames.update({str(k): str(v) for k, v in value.items()",
            "                            if isinstance(v, str)})",
            "def resolves(name):",
            "    return any(os.path.isdir(os.path.join(src, name)) for src in sources)",
            "blocking, dropped = [], []",
            "for line in sys.stdin.read().splitlines():",
            '    name, _, author = line.strip().partition("\\t")',
            "    if not name or resolves(name):",
            "        continue",
            "    successor = renames.get(name)",
            "    if successor and resolves(successor):",
            "        continue",
            "    if author.strip().lower() in ODOO_AUTHORS:",
            "        dropped.append(name)",
            "    else:",
            "        blocking.append(name)",
            "for name in dropped:",
            '    print("[coverage] %s is not in %s and is not renamed — Odoo dropped it; '
            'OpenUpgrade removes it" % (name, version), file=sys.stderr)',
            "for name in blocking:",
            '    print("[coverage] %s missing for %s — place it in %s" % (name, version, customdir),',
            "          file=sys.stderr)",
            "sys.exit(1 if blocking else 0)",
            "PYCOV",
            "}",
        ]
    )


def _render_preflight_db(env: MigrationEnv) -> str:
    """Bash database-scope preflight, run right after the fresh 00_source restore
    (a resumed database is mid-chain, so the version check only holds there):
    declared-source match from ir_module_module, then per-step addons coverage.

    Coverage asks for each module's author as well as its name, because that is
    what separates a core module Odoo dropped (the upgrade removes it) from code
    the step genuinely needs."""
    source_major = odoo_major(env.source)
    lines = [
        _render_coverage_helper(),
        "",
        "preflight_db() {",
        "  local base_ver blocking=0",
        '  base_ver=$(psql -d "$DB" -tAc "SELECT latest_version FROM ir_module_module WHERE name=\'base\'")',
        f'  case "$base_ver" in {source_major}.*) ;; *) fail "database base version \'$base_ver\' does not match declared source {env.source}";; esac',
        '  modules_tsv=$(psql -d "$DB" -tAc "SELECT name || E\'\\t\' || coalesce(author, \'\') FROM ir_module_module WHERE state=\'installed\' ORDER BY name")',
    ]
    for version in env.chain():
        # The step's own add-ons path, so coverage asks exactly what the step
        # will be able to resolve — including the <= 13 fork layout.
        sources = " ".join(f'"{p}"' for p in env.addons_path(version).split(","))
        apriori = env.openupgrade_clone_dir(version) / "openupgrade_scripts" / "apriori.py"
        lines += [
            f"  # coverage: step {version}",
            f'  echo "$modules_tsv" | coverage_step "{version}" "{apriori}" '
            f'"{env.addons_custom_dir(version)}" {sources} || blocking=1',
        ]
    lines += [
        '  [ "$blocking" = 0 ] || fail "addons coverage incomplete (see [coverage] lines above)"',
        '  echo "[preflight] database checks passed"',
        "}",
    ]
    return "\n".join(lines)


def render_run_migration_sh(env: MigrationEnv) -> str:
    """The checkpointing driver: preflight the host, restore a source dump into a
    working DB (verifying it before step 1), then run each step in order, dumping
    a checkpoint after each success so a re-run resumes from the last good step
    (never touches the source/production database)."""
    header = f"""#!/usr/bin/env bash
# Generated by odoo_dwg — OpenUpgrade migration {env.source} -> {env.target}.
set -euo pipefail

SRC_DUMP="${{1:?usage: run_migration.sh <source-db-custom-format-dump>}}"
DB="{env.working_db}"
export PGHOST="{env.db_host}" PGPORT="{env.db_port}" PGUSER="{env.db_user}"
CK="{env.checkpoints_dir}"
LOGS="{env.logs_dir}"
mkdir -p "$CK" "$LOGS"

fail() {{ echo "[preflight-fail] $1" >&2; exit 1; }}

{_render_preflight_host(env)}

{_render_preflight_db(env)}

have_ck() {{ [ -f "$CK/$1.dump" ]; }}
checkpoint() {{ pg_dump -Fc "$DB" > "$CK/$1.dump"; echo "[checkpoint] $1"; }}

preflight_host

if ! have_ck 00_source; then
  echo "[init] restoring source dump into working DB '$DB'"
  dropdb --if-exists "$DB"
  createdb "$DB"
  pg_restore --no-owner --dbname "$DB" "$SRC_DUMP"
  preflight_db
  checkpoint 00_source
else
  echo "[init] resuming — source checkpoint present"
fi
"""
    steps: list[str] = []
    for version in env.chain():
        layout = "legacy layout" if env.uses_legacy_layout(version) else "upgrade-path layout"
        steps.append(
            f"""
# --- step: upgrade to {version} ({layout}) ---
if have_ck "{version}"; then
  echo "[skip] {version} already migrated"
else
  echo "[step] upgrading to {version} ({layout})"
  {_native_step_command(env, version)}
  checkpoint "{version}"
fi"""
        )
    footer = f'\n\necho "[done] migration complete — working DB is now Odoo {env.target}"\n'
    return header + "".join(steps) + footer
